<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';

$siteSettings = getSiteSettings($pdo);
$eventId = max(0, (int)($_GET['event_id'] ?? 0));
if (!$currentUser) { header('Location: /account'); exit; }
$event = fetchEventById($pdo, $eventId);
$notes = fetchRideNotes($pdo, $eventId);
$role = strtolower((string)($currentUser['role'] ?? ''));
$preview = !empty($_GET['preview']) && in_array($role, ['superadmin', 'admin', 'organiser'], true);
if (!$event || !$notes || (($notes['status'] ?? 'draft') !== 'complete' && !$preview)) { http_response_code(404); $event = null; }
$rideBatch = $event ? mediaBatchFind($pdo, 'ride_notes_images', 'event', $eventId) : null;
$rideImages = $rideBatch ? mediaBatchImages($pdo, (int)$rideBatch['id']) : [];
if ($rideImages) $notes['ride_notes_html'] = '<div style="display:flex;align-items:flex-start;gap:24px"><div style="flex:0 0 38%;min-width:220px"><img src="'.h(mediaBatchImageUrl($rideBatch,$rideImages[0],'md')).'" style="display:block;width:100%;height:auto;border-radius:8px" alt="'.h($rideImages[0]['alt_text']??'Ride Notes image').'" /></div><div style="flex:1;min-width:0">'.($notes['ride_notes_html']??'').'</div></div>';
$venue = $event && !empty($event['venue_id']) ? fetchVenueById($pdo,(int)$event['venue_id']) : null;
$venueBatch = $venue ? mediaBatchFind($pdo,'venue_images','venue',(int)$venue['id']) : null;
$venueImages = $venueBatch ? mediaBatchImages($pdo,(int)$venueBatch['id']) : [];
$brand = trim((string)($siteSettings['company_name']??'')) ?: 'ILDRA';
$logo = trim((string)($siteSettings['ride_notes_email_header_image_url']??$siteSettings['sponsor_image_url']??''));
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>body{background:#f7f8f1}.head,.actions{background:#fff;border-bottom:1px solid #dbe5d8}.head .in{min-height:76px;display:flex;justify-content:center;align-items:center;gap:1rem}.brand{font-size:1.65rem;font-weight:800;color:#146118}.logo{max-height:76px;max-width:150px;object-fit:contain}.actions .in{padding:.6rem 0;display:flex;justify-content:flex-end;gap:.5rem}.card{border-radius:12px}.label{font-size:.76rem;color:#6c757d;text-transform:uppercase;font-weight:700}.main-img{width:100%;max-height:380px;object-fit:contain}.thumb{width:76px;height:58px;object-fit:cover}.print{background:#146118;color:#fff}@media print{.actions,.alert{display:none}.container{max-width:none!important;width:100%!important}}</style></head><body>
<header class="head"><div class="container in"><?php if($logo): ?><img class="logo" src="<?php echo h($logo); ?>"><?php endif; ?><div class="brand"><?php echo h($brand); ?></div></div></header><div class="actions"><div class="container in"><a class="btn btn-sm btn-outline-secondary" href="/" target="_blank">Website Home</a><button class="btn btn-sm print" onclick="window.print()">Print</button></div></div>
<main class="container py-4"><?php if(!$event): ?><h1 class="h3">Ride Notes unavailable</h1><?php else: ?><?php if($preview): ?><div class="alert alert-warning">Admin preview — this Ride Notes page is still a draft.</div><?php endif; ?><section class="card bg-white p-4 mb-4"><h1 class="h3 mb-4">Ride Information</h1><div class="row g-3"><div class="col-md-4"><div class="label">Ride Name</div><strong><?php echo h($event['title']); ?></strong></div><div class="col-md-3"><div class="label">Venue</div><strong><?php echo h($venue['name']??$event['venue']??'—'); ?><?php echo !empty($venue['postcode'])?' · '.h($venue['postcode']):''; ?></strong></div><div class="col-md-2"><div class="label">Start Time</div><strong><?php echo h($event['start_time']??'—'); ?></strong></div><div class="col-md-3"><div class="label">Last Ride Out</div><strong><?php echo h($event['end_time']??'—'); ?></strong></div></div><hr><?php echo render_wysiwyg((string)($notes['ride_notes_html']??'')); ?><?php if(rideNotesPdfAttachment($notes)): ?><div class="mt-4"><a class="btn btn-outline-success" target="_blank" rel="noopener" href="<?php echo h(rideNotesPdfUrl((string)$notes['pdf_filename'])); ?>"><i class="fa-solid fa-file-pdf"></i> Download Ride Notes PDF</a></div><?php endif; ?></section>
<?php if($venue): ?><section class="card bg-white p-4 mb-4"><h2 class="h4">Venue</h2><div class="row g-4"><?php if($venueImages): ?><div class="col-md-5"><img class="main-img" src="<?php echo h(mediaBatchImageUrl($venueBatch,$venueImages[0],'md')); ?>"><?php foreach(array_slice($venueImages,1)as$image): ?><a href="<?php echo h(mediaBatchImageUrl($venueBatch,$image,'original')); ?>" target="_blank"><img class="thumb m-1" src="<?php echo h(mediaBatchImageUrl($venueBatch,$image,'xs')); ?>"></a><?php endforeach; ?></div><?php endif; ?><div class="<?php echo $venueImages?'col-md-7':'col-12'; ?>"><?php echo render_wysiwyg((string)($venue['notes']??'')); ?><?php if(!empty($venue['directions'])): ?><div class="mt-3"><?php echo render_wysiwyg((string)$venue['directions']); ?></div><?php endif; ?></div></div><?php if(!empty($venue['google_url'])): ?><a class="btn btn-sm btn-outline-secondary mt-3" href="<?php echo h($venue['google_url']); ?>" target="_blank"><i class="fa-solid fa-map-location-dot"></i> View on Google Maps</a><?php endif; ?></section><?php endif; ?><?php if(trim((string)($notes['ctr_notes_html']??''))!==''): ?><section class="card bg-white p-4"><h2 class="h4">Competitive Riders</h2><?php echo render_wysiwyg((string)$notes['ctr_notes_html']); ?></section><?php endif; ?><?php endif; ?></main></body></html>
