<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php'; require_once __DIR__ . '/table_sort.php';
if (!in_array(strtolower((string)($currentUser['role'] ?? '')), ['superadmin','admin','manager'], true)) { header('Location:index.php'); exit; }
ensureAwardsTables($pdo);
$defaultAwardYear = (int)($_SESSION['awards_last_winner_year'] ?? ((int)date('Y') - 1));
if (isset($_GET['winners_for'])) {
    header('Location: award_winners.php?award_id=' . (int)$_GET['winners_for'] . (!empty($_GET['edit_winner']) ? '&edit_winner=' . (int)$_GET['edit_winner'] : ''));
    exit;
}
if (isset($_GET['award_id'])) { header('Location: award_edit.php?id=' . (int)$_GET['award_id']); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action=(string)($_POST['action']??'');
    if ($action==='save_winner') {
        $id=(int)($_POST['winner_id']??0);$awardId=(int)($_POST['award_id']??0);$year=(int)($_POST['award_year']??((int)date('Y') - 1));$winner=trim((string)($_POST['winner_name']??''));
        if($awardId<=0||$year<1900||$winner==='')$alerts[]=['type'=>'danger','message'=>'Award, year and winner are required.'];
        if (!array_key_exists('is_published', $_POST)) $_POST['is_published'] = 1;
        if(!$alerts){$data=[':award'=>$awardId,':year'=>$year,':winner'=>$winner,':published'=>!empty($_POST['is_published'])?1:0,':archived'=>!empty($_POST['is_archived'])?1:0];if($id){$data[':id']=$id;$sql='UPDATE award_winners SET award_id=:award,award_year=:year,winner_name=:winner,is_published=:published,is_archived=:archived WHERE id=:id';}else $sql='INSERT INTO award_winners(award_id,award_year,winner_name,is_published,is_archived) VALUES(:award,:year,:winner,:published,:archived)';$pdo->prepare($sql)->execute($data);$_SESSION['awards_last_winner_year']=$year;$_SESSION['flash_success']='Winner saved.';header('Location:awards.php'.(!empty($_POST['return_to'])?'?'.ltrim((string)$_POST['return_to'],'?'):''));exit;}
    } elseif ($action==='delete_winner') {$pdo->prepare('DELETE FROM award_winners WHERE id=:id')->execute([':id'=>(int)$_POST['id']]);$_SESSION['flash_success']='Winner deleted.';header('Location:awards.php?'.ltrim((string)($_POST['return_to']??''),'?'));exit;}
    elseif ($action==='save_award') {$id=(int)($_POST['award_id']??0);$name=trim((string)($_POST['name']??''));if($name==='')$alerts[]=['type'=>'danger','message'=>'Award name is required.'];if(!$alerts){$d=[':name'=>$name,':description'=>trim((string)($_POST['description_html']??''))?:null,':asset'=>(int)($_POST['image_asset_id']??0)?:null,':order'=>(int)($_POST['display_order']??100),':published'=>!empty($_POST['is_published'])?1:0,':archived'=>!empty($_POST['is_archived'])?1:0];if($id){$d[':id']=$id;$sql='UPDATE award_catalog SET name=:name,description_html=:description,image_asset_id=:asset,display_order=:order,is_published=:published,is_archived=:archived WHERE id=:id';}else $sql='INSERT INTO award_catalog(name,description_html,image_asset_id,display_order,is_published,is_archived) VALUES(:name,:description,:asset,:order,:published,:archived)';$pdo->prepare($sql)->execute($d);$_SESSION['flash_success']='Award saved.';header('Location:awards.php');exit;}}
}
$awards=fetchAwards($pdo);$winnerRows=fetchAwardWinners($pdo);$winnerCounts=[];foreach($winnerRows as $r)$winnerCounts[(int)$r['award_id']]=($winnerCounts[(int)$r['award_id']]??0)+1;
$filterForm='awards-filter-form';$columns=['name'=>['label'=>'Award','field'=>'name','sortable'=>true,'filter'=>'text','form'=>$filterForm],'winners'=>['label'=>'Winners','sortable'=>true,'filter'=>'text','compare'=>'number','form'=>$filterForm,'value'=>fn($r)=>(string)($winnerCounts[(int)$r['id']]??0)],'order'=>['label'=>'Order','field'=>'display_order','sortable'=>true,'filter'=>'text','compare'=>'number','form'=>$filterForm],'status'=>['label'=>'Status','sortable'=>true,'filter'=>'select','options'=>['published'=>'Published','hidden'=>'Hidden','archived'=>'Archived'],'form'=>$filterForm,'value'=>fn($r)=>!empty($r['is_archived'])?'archived':(!empty($r['is_published'])?'published':'hidden')]];$table=admin_table_prepare($awards,$columns,'order');
$editAwardId=(int)($_GET['award_id']??0);$editAward=null;foreach($awards as $a)if((int)$a['id']===$editAwardId)$editAward=$a;$assets=fetchAssetLibrary($pdo,true);$winnersFor=(int)($_GET['winners_for']??0);$pastWinners=$winnersFor?fetchAwardWinners($pdo,$winnersFor):[];$pastAward=null;foreach($awards as $a)if((int)$a['id']===$winnersFor)$pastAward=$a;$editWinnerId=(int)($_GET['edit_winner']??0);$editWinner=null;foreach($pastWinners as $winner)if((int)$winner['id']===$editWinnerId)$editWinner=$winner;
admin_layout_start('Awards','awards');
?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Awards and winner history</div><h5 class="mb-0">Awards</h5></div><a class="btn btn-success" href="awards.php?award_id=0">Add award</a></div>
<?php if ($editAward!==null || isset($_GET['award_id'])): $editAward=$editAward?:['id'=>0,'name'=>'','description_html'=>'','image_asset_id'=>0,'display_order'=>100,'is_published'=>1,'is_archived'=>0]; ?><div class="card-soft p-4 mb-4"><h6><?php echo $editAwardId?'Edit award':'Add award'; ?></h6><form method="post" class="row g-3"><input type="hidden" name="action" value="save_award"><input type="hidden" name="award_id" value="<?php echo (int)$editAward['id']; ?>"><div class="col-md-6"><label class="form-label">Award name</label><input class="form-control" name="name" required value="<?php echo h($editAward['name']); ?>"></div><div class="col-md-3"><label class="form-label">Order</label><input class="form-control" type="number" name="display_order" value="<?php echo (int)$editAward['display_order']; ?>"></div><div class="col-md-3"><label class="form-label">Image</label><select class="form-select" name="image_asset_id"><option value="0">Holding image</option><?php foreach($assets as $asset):if(($asset['asset_type']??'')!=='image')continue;?><option value="<?php echo (int)$asset['id']; ?>" <?php echo (int)$editAward['image_asset_id']===(int)$asset['id']?'selected':''; ?>><?php echo h($asset['title']?:$asset['name']); ?></option><?php endforeach;?></select></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control wysiwyg-field" name="description_html" rows="6"><?php echo h($editAward['description_html']); ?></textarea></div><div class="col-12"><label class="me-3"><input type="checkbox" name="is_published" <?php echo $editAward['is_published']?'checked':''; ?>> Published</label><label><input type="checkbox" name="is_archived" <?php echo $editAward['is_archived']?'checked':''; ?>> Archived</label></div><div><button class="btn btn-success">Save award</button> <a class="btn btn-outline-secondary" href="awards.php">Cancel</a></div></form></div><?php endif; ?>
<form method="get" id="<?php echo h($filterForm); ?>"></form><div class="card-soft p-3"><div class="d-flex justify-content-between"><h6>Awards</h6><?php echo admin_table_record_count($table,'award','awards'); ?></div><div class="table-responsive"><table class="table table-sm align-middle"><thead class="table-light"><tr><?php foreach($columns as $key=>$column):?><th><?php echo admin_table_heading($key,$column,$table['sort_key'],$table['sort_dir']); ?></th><?php endforeach;?><th class="text-end">Actions</th></tr><tr class="admin-table-filter-row"><?php foreach($columns as $key=>$column):?><th><?php echo admin_table_filter($key,$column,$table['filters']); ?></th><?php endforeach;?><th class="text-end"><button class="btn btn-sm btn-outline-secondary" form="<?php echo h($filterForm); ?>">Filter</button> <a class="btn btn-sm btn-link" href="awards.php">Clear</a></th></tr></thead><tbody><?php foreach($table['rows'] as $award):?><tr><td class="fw-semibold"><?php echo h($award['name']); ?></td><td><?php echo (int)($winnerCounts[(int)$award['id']]??0); ?></td><td><?php echo (int)$award['display_order']; ?></td><td><?php echo $award['is_archived']?'Archived':($award['is_published']?'Published':'Hidden'); ?></td><td class="text-end"><button type="button" class="btn btn-sm btn-success" data-bs-toggle="modal" data-bs-target="#addWinnerModal" data-award-id="<?php echo (int)$award['id']; ?>" data-award-name="<?php echo h($award['name']); ?>">Add winner</button> <a class="btn btn-sm btn-outline-primary" href="awards.php?winners_for=<?php echo (int)$award['id']; ?>">Past winners</a> <a class="btn btn-sm btn-outline-secondary" href="awards.php?award_id=<?php echo (int)$award['id']; ?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div><?php echo admin_table_pagination($table); ?></div>
<?php if($pastAward):?><div class="card-soft p-3 mt-4"><div class="d-flex justify-content-between"><h6>Past winners: <?php echo h($pastAward['name']); ?></h6><a class="btn btn-sm btn-outline-secondary" href="awards.php">Close</a></div><?php if($editWinner):?><form method="post" class="row g-2 mb-3"><input type="hidden" name="action" value="save_winner"><input type="hidden" name="winner_id" value="<?php echo (int)$editWinner['id']; ?>"><input type="hidden" name="award_id" value="<?php echo (int)$pastAward['id']; ?>"><input type="hidden" name="return_to" value="winners_for=<?php echo (int)$pastAward['id']; ?>"><div class="col-md-3"><input class="form-control" type="number" name="award_year" value="<?php echo (int)$editWinner['award_year']; ?>"></div><div class="col-md-6"><input class="form-control" name="winner_name" value="<?php echo h($editWinner['winner_name']); ?>"></div><div class="col-md-3"><button class="btn btn-success">Save winner</button></div></form><?php endif;?><table class="table table-sm"><thead><tr><th>Year</th><th>Winner</th><th></th></tr></thead><tbody><?php foreach($pastWinners as $winner):?><tr><td><?php echo (int)$winner['award_year']; ?></td><td><?php echo h($winner['winner_name']); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="awards.php?winners_for=<?php echo (int)$pastAward['id']; ?>&edit_winner=<?php echo (int)$winner['id']; ?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div><?php endif; ?>
<div class="modal fade" id="addWinnerModal" tabindex="-1"><div class="modal-dialog"><form method="post" class="modal-content"><input type="hidden" name="action" value="save_winner"><input type="hidden" name="award_id" id="quick-award-id"><div class="modal-header"><h5 class="modal-title">Add winner</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Award</label><div class="form-control bg-light" id="quick-award-name"></div></div><div class="mb-3"><label class="form-label">Year</label><input class="form-control" type="number" name="award_year" value="<?php echo $defaultAwardYear; ?>" required></div><div><label class="form-label">Winner</label><input class="form-control" name="winner_name" required autofocus></div></div><div class="modal-footer"><button class="btn btn-success">Add winner</button></div></form></div></div>
<?php render_tinymce_bootstrap(); ?><script>if(window.tinymce)tinymce.init(window.ildraTinyMceConfig({selector:'textarea.wysiwyg-field'}));document.getElementById('addWinnerModal').addEventListener('show.bs.modal',e=>{let b=e.relatedTarget;document.getElementById('quick-award-id').value=b.dataset.awardId;document.getElementById('quick-award-name').textContent=b.dataset.awardName;});</script><?php admin_layout_end();
