<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';

$roleKey=strtolower((string)($currentUser['role']??''));
if(!in_array($roleKey,['superadmin','admin','manager'],true)){header('Location: '.$adminBase.'/index.php');exit;}
ensureEmailCampaignTables($pdo);
if(empty($_SESSION['campaign_csrf']))$_SESSION['campaign_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['campaign_csrf']; $view=(string)($_GET['view']??'list'); $id=max(0,(int)($_GET['id']??$_POST['id']??0));

function campaign_admin_row(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT * FROM email_campaigns WHERE id=:id LIMIT 1');$s->execute([':id'=>$id]);return $s->fetch()?:null; }
function campaign_admin_redirect(int $id,string $message): void { $_SESSION['flash_success']=$message;header('Location: campaigns.php?view=edit&id='.$id);exit; }

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??'')))$alerts[]=['type'=>'danger','message'=>'Your session token expired. Please try again.'];
    else{
        $action=(string)($_POST['action']??'');
        if($action==='save'){
            $validationAlertCount=count($alerts);
            $name=trim((string)($_POST['name']??''));$subject=trim((string)($_POST['subject_template']??''));$html=trim((string)($_POST['html_template']??''));
            $category=in_array((string)($_POST['category']??''),['operational','general','ride_notice'],true)?(string)$_POST['category']:'general';
            $preset=array_key_exists((string)($_POST['audience_preset']??''),emailCampaignPresets())?(string)$_POST['audience_preset']:'all_users';
            $strategy=in_array((string)($_POST['address_strategy']??''),['person_first','account_only','person_only'],true)?(string)$_POST['address_strategy']:'person_first';
            $schedule=trim((string)($_POST['scheduled_at']??''));$schedule=$schedule!==''?str_replace('T',' ',$schedule).(strlen($schedule)===16?':00':''):null;
            $batch=max(1,min(500,(int)($_POST['batch_size']??25)));$eventId=max(0,(int)($_POST['event_id']??0));$year=max(2000,min(2100,(int)($_POST['membership_year']??date('Y'))));
            if($name===''||$subject===''||$html==='')$alerts[]=['type'=>'danger','message'=>'Name, subject and HTML message are required.'];
            if($preset==='event_entrants'&&$eventId<=0)$alerts[]=['type'=>'danger','message'=>'Choose an event for an entrant campaign.'];
            if($schedule!==null){$scheduleDate=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$schedule,new DateTimeZone('Europe/London'));$scheduleErrors=DateTimeImmutable::getLastErrors();if(!$scheduleDate||($scheduleErrors&&($scheduleErrors['warning_count']||$scheduleErrors['error_count'])))$alerts[]=['type'=>'danger','message'=>'Enter a valid UK-local schedule date and time.'];elseif((int)$scheduleDate->format('i')%15!==0)$alerts[]=['type'=>'danger','message'=>'Schedule campaigns on a 15-minute boundary.'];else$schedule=$scheduleDate->format('Y-m-d H:i:s');}
            if(count($alerts)===$validationAlertCount){
                if($id){$s=$pdo->prepare("UPDATE email_campaigns SET name=:name,category=:category,audience_preset=:preset,event_id=:event,membership_year=:year,address_strategy=:strategy,subject_template=:subject,html_template=:html,text_template=:text,scheduled_at=:scheduled,batch_size=:batch,status=IF(status IN ('sent','sending'),status,'draft'),live_send_approved=0,approved_by_user_id=NULL,approved_at=NULL WHERE id=:id");}
                else{$s=$pdo->prepare("INSERT INTO email_campaigns (name,campaign_type,category,audience_preset,event_id,membership_year,address_strategy,subject_template,html_template,text_template,scheduled_at,batch_size,created_by_user_id) VALUES (:name,'announcement',:category,:preset,:event,:year,:strategy,:subject,:html,:text,:scheduled,:batch,:created)");}
                $p=[':name'=>$name,':category'=>$category,':preset'=>$preset,':event'=>$eventId?:null,':year'=>$year,':strategy'=>$strategy,':subject'=>$subject,':html'=>$html,':text'=>trim((string)($_POST['text_template']??''))?:null,':scheduled'=>$schedule,':batch'=>$batch];
                if($id)$p[':id']=$id;else$p[':created']=(int)$currentUser['id'];$s->execute($p);if(!$id)$id=(int)$pdo->lastInsertId();campaign_admin_redirect($id,'Campaign saved. Live approval was reset.');
            }
        } elseif($id>0&&$action==='snapshot'){$result=emailCampaignSnapshotRecipients($pdo,$id);campaign_admin_redirect($id,$result['count'].' unique recipients prepared; '.$result['skipped'].' invalid or non-consenting records skipped.');}
        elseif($id>0&&$action==='send_test'){
            $to=trim((string)($_POST['test_email']??''));$campaign=campaign_admin_row($pdo,$id);
            if(!filter_var($to,FILTER_VALIDATE_EMAIL))$alerts[]=['type'=>'danger','message'=>'Enter a valid test email address.'];
            elseif($campaign){$settings=getSiteSettings($pdo);$merge=array_merge(emailCampaignEventMerge($pdo,(int)($campaign['event_id']??0),emailCampaignBaseUrl($settings)),['campaign_name'=>$campaign['name'],'first_name'=>(string)($currentUser['first_name']??'Test'),'last_name'=>(string)($currentUser['last_name']??''),'full_name'=>trim((string)($currentUser['first_name']??'').' '.(string)($currentUser['last_name']??'')),'email'=>$to,'member_number'=>'TEST','membership_year'=>(string)($campaign['membership_year']??date('Y')),'current_date'=>emailCampaignLocalNow()->format('j F Y'),'membership_url'=>emailCampaignBaseUrl($settings).'/memberships','logbook_url'=>emailCampaignBaseUrl($settings).'/logbooks','message'=>'This is test content.']);$fake=['merge_json'=>json_encode($merge),'tracking_token'=>'test','unsubscribe_token'=>'test'];$payload=emailCampaignRenderRecipient($campaign,$fake,$settings);$ok=send_logged_email($pdo,$to,subject_with_prefix(getEmailSettings($pdo),$payload['subject']),wrap_user_email_html($settings,getEmailSettings($pdo),$payload['html']),wrap_user_email_text($settings,getEmailSettings($pdo),$payload['text']),['kind'=>'campaign_test','campaign_id'=>$id]);$alerts[]=['type'=>$ok?'success':'warning','message'=>$ok?'Test email sent.':'Test email was not sent. Check the email log and delivery safety settings.'];}
        } elseif($id>0&&$action==='schedule'){
            $campaign=campaign_admin_row($pdo,$id);$count=$campaign?(int)$campaign['recipient_count']:0;
            if($count<=0)$alerts[]=['type'=>'danger','message'=>'Prepare the recipient snapshot before scheduling.'];
            elseif($roleKey!=='superadmin')$alerts[]=['type'=>'danger','message'=>'Only a Superadmin can approve a live campaign.'];
            else{$scheduled=trim((string)($campaign['scheduled_at']??''))?:emailCampaignLocalNow()->format('Y-m-d H:i:s');$s=$pdo->prepare("UPDATE email_campaigns SET status='scheduled',scheduled_at=:scheduled,live_send_approved=1,approved_by_user_id=:user,approved_at=NOW() WHERE id=:id");$s->execute([':scheduled'=>$scheduled,':user'=>(int)$currentUser['id'],':id'=>$id]);campaign_admin_redirect($id,'Campaign approved and scheduled. The global campaign live-send lock still applies.');}
        }
    }
}

$templates=$pdo->query('SELECT * FROM email_campaign_templates WHERE is_active=1 ORDER BY name')->fetchAll()?:[];
$events=$pdo->query("SELECT id,title,event_date FROM events WHERE event_date>=DATE_SUB(CURDATE(),INTERVAL 3 MONTH) ORDER BY event_date DESC")->fetchAll()?:[];
if($view==='new'&&isset($_GET['template'])){$key=(string)$_GET['template'];$s=$pdo->prepare('SELECT * FROM email_campaign_templates WHERE template_key=:key LIMIT 1');$s->execute([':key'=>$key]);$template=$s->fetch()?:null;}else$template=null;

if($view==='edit'||$view==='new'){
    $campaign=$id?campaign_admin_row($pdo,$id):null;
    $campaign=$campaign?:['name'=>$template['name']??'','category'=>$template['category']??'general','audience_preset'=>'all_users','event_id'=>0,'membership_year'=>date('Y'),'address_strategy'=>'person_first','subject_template'=>$template['subject_template']??'','html_template'=>$template['html_template']??'','text_template'=>$template['text_template']??'','scheduled_at'=>'','batch_size'=>(int)(getSiteSettings($pdo)['campaign_default_batch_size']??25),'status'=>'draft','recipient_count'=>0,'sent_count'=>0,'failed_count'=>0,'opened_count'=>0,'live_send_approved'=>0];
    $campaignEmailSettings=getEmailSettings($pdo);$campaignProvider=(string)($campaignEmailSettings['email_provider']??'smtp');$campaignTransportLabel=$campaignProvider==='smtp'?'SMTP via '.(string)($campaignEmailSettings['email_smtp_host']??'not configured').':'.(int)($campaignEmailSettings['email_smtp_port']??587):'PHP mail()';
    admin_layout_start($id?'Edit Campaign':'New Campaign','email_campaigns');?>
    <div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Email campaigns</div><h5 class="mb-0"><?php echo h((string)$campaign['name']?:'New campaign'); ?></h5></div><a class="btn btn-outline-secondary" href="campaigns.php">Back</a></div>
    <?php if($id): ?><div class="alert <?php echo !empty($campaign['live_send_approved'])?'alert-warning':'alert-secondary'; ?> py-2">Status: <strong><?php echo h((string)$campaign['status']); ?></strong> · Recipients: <?php echo (int)$campaign['recipient_count']; ?> · Sent: <?php echo (int)$campaign['sent_count']; ?> · Failed: <?php echo (int)$campaign['failed_count']; ?> · Opened: <?php echo (int)$campaign['opened_count']; ?><?php if(empty($campaign['live_send_approved'])): ?> · Live sending not approved<?php endif; ?></div><?php endif; ?>
    <form method="post" class="card-soft p-4 mb-4"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?php echo $id; ?>">
      <div class="row g-3"><div class="col-md-8"><label class="form-label">Campaign name</label><input class="form-control" name="name" value="<?php echo h((string)$campaign['name']); ?>" required></div><div class="col-md-4"><label class="form-label">Category</label><select class="form-select" name="category"><option value="operational" <?php echo $campaign['category']==='operational'?'selected':''; ?>>Operational</option><option value="general" <?php echo $campaign['category']==='general'?'selected':''; ?>>General opt-in</option><option value="ride_notice" <?php echo $campaign['category']==='ride_notice'?'selected':''; ?>>Ride Notice opt-in</option></select></div>
      <div class="col-md-4"><label class="form-label">Audience</label><select class="form-select" name="audience_preset"><?php foreach(emailCampaignPresets() as $key=>$label): ?><option value="<?php echo h($key); ?>" <?php echo $campaign['audience_preset']===$key?'selected':''; ?>><?php echo h($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-md-4"><label class="form-label">Event where applicable</label><select class="form-select" name="event_id"><option value="0">None</option><?php foreach($events as $event): ?><option value="<?php echo (int)$event['id']; ?>" <?php echo (int)$campaign['event_id']===(int)$event['id']?'selected':''; ?>><?php echo h(format_display_date($event['event_date'],'').' · '.$event['title']); ?></option><?php endforeach; ?></select></div>
      <div class="col-md-2"><label class="form-label">Membership year</label><input class="form-control" type="number" min="2000" max="2100" step="1" name="membership_year" value="<?php echo (int)$campaign['membership_year']; ?>"></div><div class="col-md-2"><label class="form-label">Batch size</label><input class="form-control" type="number" min="1" max="500" step="1" name="batch_size" value="<?php echo (int)$campaign['batch_size']; ?>"></div>
      <div class="col-md-4"><label class="form-label">Email address choice</label><select class="form-select" name="address_strategy"><option value="person_first" <?php echo $campaign['address_strategy']==='person_first'?'selected':''; ?>>Person first, account fallback</option><option value="account_only" <?php echo $campaign['address_strategy']==='account_only'?'selected':''; ?>>Account only</option><option value="person_only" <?php echo $campaign['address_strategy']==='person_only'?'selected':''; ?>>Person only</option></select></div><div class="col-md-4"><label class="form-label">Schedule (UK local time)</label><input class="form-control" type="datetime-local" name="scheduled_at" value="<?php echo h($campaign['scheduled_at']?date('Y-m-d\TH:i',strtotime((string)$campaign['scheduled_at'])):''); ?>" step="900"></div>
      <div class="col-12"><label class="form-label">Subject</label><input class="form-control" name="subject_template" value="<?php echo h((string)$campaign['subject_template']); ?>" required></div><div class="col-12"><label class="form-label">HTML message</label><textarea class="form-control wysiwyg-field" rows="12" name="html_template"><?php echo h((string)$campaign['html_template']); ?></textarea></div><div class="col-12"><label class="form-label">Plain-text message</label><textarea class="form-control" rows="7" name="text_template"><?php echo h((string)$campaign['text_template']); ?></textarea></div>
      <div class="col-12 small text-muted">Merge fields: {{first_name}}, {{full_name}}, {{email}}, {{member_number}}, {{membership_year}}, {{event_title}}, {{event_date}}, {{event_venue}}, {{entry_close_date}}, {{event_url}}, {{ride_notes_url}}, {{membership_url}}, {{logbook_url}}, {{current_date}}.</div><div class="col-12"><button class="btn btn-success">Save campaign</button></div></div></form>
    <?php if($id&&in_array((string)$campaign['status'],['draft','paused','scheduled'],true)): ?><div class="row g-3"><div class="col-md-4"><form method="post" class="card-soft p-3 h-100"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="snapshot"><input type="hidden" name="id" value="<?php echo $id; ?>"><h6>1. Prepare recipients</h6><p class="small text-muted">Creates a deduplicated, consent-checked snapshot.</p><button class="btn btn-outline-success">Prepare snapshot</button></form></div><div class="col-md-4"><form method="post" class="card-soft p-3 h-100"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="send_test"><input type="hidden" name="id" value="<?php echo $id; ?>"><h6>2. Test</h6><div class="small text-muted mb-2"><?php echo h($campaignTransportLabel); ?></div><input class="form-control mb-2" type="email" name="test_email" value="<?php echo h((string)($currentUser['email']??'')); ?>" required><button class="btn btn-outline-primary">Send test</button></form></div><div class="col-md-4"><form method="post" class="card-soft p-3 h-100"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="schedule"><input type="hidden" name="id" value="<?php echo $id; ?>"><h6>3. Approve</h6><p class="small text-muted">Superadmin only. Campaign delivery also requires the global live-send switch.</p><button class="btn btn-warning" <?php echo $roleKey!=='superadmin'?'disabled':''; ?>>Approve and schedule</button></form></div></div><?php endif; ?>
    <?php if($id): $recipientStmt=$pdo->prepare('SELECT * FROM email_campaign_recipients WHERE campaign_id=:id ORDER BY id DESC LIMIT 200');$recipientStmt->execute([':id'=>$id]);$recipientRows=$recipientStmt->fetchAll()?:[]; ?>
    <div class="card-soft p-4 mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="mb-0">Recipient report</h6><span class="small text-muted">Open counts are approximate</span></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Recipient</th><th>Status</th><th>Sent</th><th>Opened</th><th>Email log</th></tr></thead><tbody><?php if(!$recipientRows): ?><tr><td colspan="5" class="text-muted">Prepare a recipient snapshot to populate this report.</td></tr><?php endif; ?><?php foreach($recipientRows as $recipientRow): ?><tr><td><?php echo h(trim((string)$recipientRow['first_name'].' '.(string)$recipientRow['last_name'])); ?><div class="small text-muted"><?php echo h((string)$recipientRow['email']); ?></div></td><td><?php echo h(ucfirst((string)$recipientRow['status'])); ?><?php if($recipientRow['error_message']): ?><div class="small text-danger"><?php echo h((string)$recipientRow['error_message']); ?></div><?php endif; ?></td><td><?php echo $recipientRow['sent_at']?h(date('d M Y H:i',strtotime((string)$recipientRow['sent_at']))):'—'; ?></td><td><?php echo (int)$recipientRow['open_count']; ?><?php if($recipientRow['first_opened_at']): ?><div class="small text-muted">First <?php echo h(date('d M Y H:i',strtotime((string)$recipientRow['first_opened_at']))); ?></div><?php endif; ?></td><td><?php if($recipientRow['email_log_id']): ?><a href="email_view.php?id=<?php echo (int)$recipientRow['email_log_id']; ?>">#<?php echo (int)$recipientRow['email_log_id']; ?></a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
    <?php render_tinymce_bootstrap(); ?><script>if(window.tinymce)tinymce.init(window.ildraTinyMceConfig({selector:'textarea.wysiwyg-field'}));</script><?php admin_layout_end();exit;
}

$rows=$pdo->query('SELECT c.*,e.title event_title FROM email_campaigns c LEFT JOIN events e ON e.id=c.event_id ORDER BY c.id DESC')->fetchAll()?:[];
admin_layout_start('Email Campaigns','email_campaigns');?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><div class="text-muted">Email campaigns</div><div class="small text-muted">Templates, audiences, scheduling and delivery reports</div></div><div class="dropdown"><button class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown">New campaign</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="campaigns.php?view=new">Blank campaign</a></li><?php foreach($templates as $t): ?><li><a class="dropdown-item" href="campaigns.php?view=new&amp;template=<?php echo h((string)$t['template_key']); ?>"><?php echo h((string)$t['name']); ?></a></li><?php endforeach; ?></ul></div></div>
<div class="card-soft p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Campaign</th><th>Audience</th><th>Status</th><th>Scheduled (UK)</th><th>Delivery</th><th></th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="6" class="text-muted">No campaigns yet.</td></tr><?php endif; ?><?php foreach($rows as $row): ?><tr><td><strong><?php echo h((string)$row['name']); ?></strong><?php if($row['event_title']): ?><div class="small text-muted"><?php echo h((string)$row['event_title']); ?></div><?php endif; ?></td><td><?php echo h(emailCampaignPresets()[$row['audience_preset']]??(string)$row['audience_preset']); ?></td><td><?php echo h(ucfirst((string)$row['status'])); ?></td><td><?php echo $row['scheduled_at']?h(date('d M Y H:i',strtotime((string)$row['scheduled_at']))):'—'; ?></td><td><?php echo (int)$row['sent_count']; ?>/<?php echo (int)$row['recipient_count']; ?> sent · <?php echo (int)$row['opened_count']; ?> opened</td><td><a class="btn btn-sm btn-outline-secondary" href="campaigns.php?view=edit&amp;id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php admin_layout_end();
