<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';

$roleKey=strtolower((string)($currentUser['role']??''));
if(!in_array($roleKey,['superadmin','admin','manager'],true)){header('Location: '.$adminBase.'/index.php');exit;}
ensureEmailCampaignTables($pdo);
if(empty($_SESSION['campaign_csrf']))$_SESSION['campaign_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['campaign_csrf']; $view=(string)($_GET['view']??'list'); $id=max(0,(int)($_GET['id']??$_POST['id']??0));

function campaign_admin_row(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT * FROM email_campaigns WHERE id=:id LIMIT 1');$s->execute([':id'=>$id]);return $s->fetch()?:null; }
function campaign_admin_redirect(int $id,string $message): void { $_SESSION['flash_success']=$message;header('Location: campaigns.php?view=edit&id='.$id);exit; }
function campaign_template_redirect(int $id,string $message): void { $_SESSION['flash_success']=$message;header('Location: campaigns.php?view=template_edit&template_id='.$id);exit; }
function campaign_admin_send_limited_test(PDO $pdo,array $campaign,int $userId): array
{
    $userStmt=$pdo->prepare("SELECT u.id,u.email,u.first_name,u.last_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=:id AND LOWER(r.name) IN ('admin','superadmin') LIMIT 1");
    $userStmt->execute([':id'=>$userId]);$user=$userStmt->fetch()?:null;
    if(!$user||!filter_var((string)$user['email'],FILTER_VALIDATE_EMAIL))return ['ok'=>false,'message'=>'Choose a valid Admin or Superadmin account.'];

    $settings=getSiteSettings($pdo);$base=emailCampaignBaseUrl($settings);$year=(int)($campaign['membership_year']??date('Y'));
    ensureMembershipTables($pdo);
    $personStmt=$pdo->prepare("SELECT p.id,p.member_number FROM people p LEFT JOIN membership_purchases mp ON mp.member_id=p.id AND mp.membership_year=:year AND mp.status<>'expired' WHERE p.owner_user_id=:user AND p.is_archived=0 ORDER BY (mp.id IS NOT NULL) DESC,p.id LIMIT 1");
    $personStmt->execute([':year'=>$year,':user'=>$userId]);$person=$personStmt->fetch()?:[];
    $first=trim((string)($user['first_name']??''));$last=trim((string)($user['last_name']??''));$email=strtolower(trim((string)$user['email']));
    $merge=array_merge(emailCampaignEventMerge($pdo,(int)($campaign['event_id']??0),$base),[
        'campaign_name'=>(string)$campaign['name'],'first_name'=>$first,'last_name'=>$last,'full_name'=>trim($first.' '.$last),
        'email'=>$email,'member_number'=>(string)($person['member_number']??''),'membership_year'=>(string)$year,
        'current_date'=>emailCampaignLocalNow()->format('j F Y'),'membership_url'=>$base.'/memberships','logbook_url'=>$base.'/logbooks',
        'message'=>'This is limited test content.','_user_id'=>$userId,'_person_id'=>(int)($person['id']??0),'_address_source'=>'account',
    ]);
    $tracking=sha1(random_bytes(32));$unsubscribe=sha1(random_bytes(32));
    $insert=$pdo->prepare("INSERT INTO email_campaign_limited_tests (campaign_id,user_id,person_id,email,category,merge_json,tracking_token,unsubscribe_token) VALUES (:campaign,:user,:person,:email,:category,:merge,:tracking,:unsubscribe)");
    $insert->execute([':campaign'=>(int)$campaign['id'],':user'=>$userId,':person'=>(int)($person['id']??0)?:null,':email'=>$email,':category'=>(string)$campaign['category'],':merge'=>json_encode($merge,JSON_UNESCAPED_SLASHES),':tracking'=>$tracking,':unsubscribe'=>$unsubscribe]);
    $limitedId=(int)$pdo->lastInsertId();$recipient=['merge_json'=>json_encode($merge,JSON_UNESCAPED_SLASHES),'tracking_token'=>$tracking,'unsubscribe_token'=>$unsubscribe];
    $payload=emailCampaignRenderRecipient($campaign,$recipient,$settings);$emailSettings=getEmailSettings($pdo);$beforeLogId=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM email_log')->fetchColumn();
    $ok=send_logged_email($pdo,$email,subject_with_prefix($emailSettings,$payload['subject']),wrap_user_email_html($settings,$emailSettings,$payload['html'],$payload['after_footer_html']),wrap_user_email_text($settings,$emailSettings,$payload['text'],$payload['after_footer_text']),['kind'=>'campaign_limited_test','campaign_id'=>(int)$campaign['id'],'limited_test_id'=>$limitedId]);
    $logStmt=$pdo->prepare('SELECT id FROM email_log WHERE id>:after_id AND meta_json LIKE :marker ORDER BY id DESC LIMIT 1');$logStmt->execute([':after_id'=>$beforeLogId,':marker'=>'%"limited_test_id":'.$limitedId.'%']);$logId=(int)($logStmt->fetchColumn()?:0);
    $pdo->prepare('UPDATE email_campaign_limited_tests SET status=:status,email_log_id=:log,sent_at=IF(:sent=1,NOW(),NULL) WHERE id=:id')->execute([':status'=>$ok?'sent':'failed',':log'=>$logId?:null,':sent'=>$ok?1:0,':id'=>$limitedId]);
    return ['ok'=>$ok,'message'=>$ok?'Limited test sent to '.$email.'.':'Limited test was not sent. Check the email log and delivery safety settings.'];
}

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??'')))$alerts[]=['type'=>'danger','message'=>'Your session token expired. Please try again.'];
    else{
        $action=(string)($_POST['action']??'');
        if($action==='save_template'){
            $templateId=max(0,(int)($_POST['template_id']??0));$name=trim((string)($_POST['name']??''));$key=preg_replace('/[^a-z0-9_]+/','_',strtolower(trim((string)($_POST['template_key']??''))))?:'';
            $renderer=in_array((string)($_POST['renderer_key']??''),['freeform','membership_renewal'],true)?(string)$_POST['renderer_key']:'freeform';
            $category=in_array((string)($_POST['category']??''),['operational','general','ride_notice','renewal_reminder'],true)?(string)$_POST['category']:'general';
            $preset=array_key_exists((string)($_POST['audience_preset']??''),emailCampaignPresets())?(string)$_POST['audience_preset']:'all_users';$subject=trim((string)($_POST['subject_template']??''));$html=trim((string)($_POST['html_template']??''));
            if($name===''||$key===''||$subject===''||($renderer==='freeform'&&$html===''))$alerts[]=['type'=>'danger','message'=>'Name, key, subject and required message content must be completed.'];
            else{
                if($templateId)$stmt=$pdo->prepare('UPDATE email_campaign_templates SET template_key=:key,name=:name,category=:category,renderer_key=:renderer,audience_preset=:audience,intro_html=:intro,outro_html=:outro,subject_template=:subject,html_template=:html,text_template=:text,is_active=:active WHERE id=:id');
                else $stmt=$pdo->prepare('INSERT INTO email_campaign_templates (template_key,name,category,renderer_key,audience_preset,intro_html,outro_html,subject_template,html_template,text_template,is_system,is_active) VALUES (:key,:name,:category,:renderer,:audience,:intro,:outro,:subject,:html,:text,0,:active)');
                $params=[':key'=>$key,':name'=>$name,':category'=>$category,':renderer'=>$renderer,':audience'=>$preset,':intro'=>trim((string)($_POST['intro_html']??'')),':outro'=>trim((string)($_POST['outro_html']??'')),':subject'=>$subject,':html'=>$html,':text'=>trim((string)($_POST['text_template']??''))?:null,':active'=>!empty($_POST['is_active'])?1:0];if($templateId)$params[':id']=$templateId;
                try{$stmt->execute($params);if(!$templateId)$templateId=(int)$pdo->lastInsertId();campaign_template_redirect($templateId,'Template saved.');}catch(PDOException $e){$alerts[]=['type'=>'danger','message'=>'The template could not be saved. Check that its key is unique.'];}
            }
        } elseif($action==='save'){
            $validationAlertCount=count($alerts);
            $name=trim((string)($_POST['name']??''));$subject=trim((string)($_POST['subject_template']??''));$html=trim((string)($_POST['html_template']??''));$renderer=in_array((string)($_POST['renderer_key']??''),['freeform','membership_renewal'],true)?(string)$_POST['renderer_key']:'freeform';$templateId=max(0,(int)($_POST['template_id']??0));
            $category=in_array((string)($_POST['category']??''),['operational','general','ride_notice','renewal_reminder'],true)?(string)$_POST['category']:'general';
            $preset=array_key_exists((string)($_POST['audience_preset']??''),emailCampaignPresets())?(string)$_POST['audience_preset']:'all_users';
            $strategy=in_array((string)($_POST['address_strategy']??''),['person_first','account_only','person_only'],true)?(string)$_POST['address_strategy']:'person_first';
            $schedule=trim((string)($_POST['scheduled_at']??''));$schedule=$schedule!==''?str_replace('T',' ',$schedule).(strlen($schedule)===16?':00':''):null;
            $batch=max(1,min(500,(int)($_POST['batch_size']??25)));$eventId=max(0,(int)($_POST['event_id']??0));$year=max(2000,min(2100,(int)($_POST['membership_year']??date('Y'))));
            if($name===''||$subject===''||($renderer==='freeform'&&$html===''))$alerts[]=['type'=>'danger','message'=>'Name, subject and required message content are required.'];
            if($preset==='event_entrants'&&$eventId<=0)$alerts[]=['type'=>'danger','message'=>'Choose an event for an entrant campaign.'];
            if($schedule!==null){$scheduleDate=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$schedule,new DateTimeZone('Europe/London'));$scheduleErrors=DateTimeImmutable::getLastErrors();if(!$scheduleDate||($scheduleErrors&&($scheduleErrors['warning_count']||$scheduleErrors['error_count'])))$alerts[]=['type'=>'danger','message'=>'Enter a valid UK-local schedule date and time.'];elseif((int)$scheduleDate->format('i')%15!==0)$alerts[]=['type'=>'danger','message'=>'Schedule campaigns on a 15-minute boundary.'];else$schedule=$scheduleDate->format('Y-m-d H:i:s');}
            if(count($alerts)===$validationAlertCount){
                if($id){$s=$pdo->prepare("UPDATE email_campaigns SET name=:name,category=:category,template_id=:template,renderer_key=:renderer,intro_html=:intro,outro_html=:outro,audience_preset=:preset,event_id=:event,membership_year=:year,address_strategy=:strategy,subject_template=:subject,html_template=:html,text_template=:text,scheduled_at=:scheduled,batch_size=:batch,status=IF(status IN ('sent','sending'),status,'draft'),live_send_approved=0,approved_by_user_id=NULL,approved_at=NULL WHERE id=:id");}
                else{$s=$pdo->prepare("INSERT INTO email_campaigns (name,campaign_type,category,template_id,renderer_key,intro_html,outro_html,audience_preset,event_id,membership_year,address_strategy,subject_template,html_template,text_template,scheduled_at,batch_size,created_by_user_id) VALUES (:name,'announcement',:category,:template,:renderer,:intro,:outro,:preset,:event,:year,:strategy,:subject,:html,:text,:scheduled,:batch,:created)");}
                $p=[':name'=>$name,':category'=>$category,':template'=>$templateId?:null,':renderer'=>$renderer,':intro'=>trim((string)($_POST['intro_html']??'')),':outro'=>trim((string)($_POST['outro_html']??'')),':preset'=>$preset,':event'=>$eventId?:null,':year'=>$year,':strategy'=>$strategy,':subject'=>$subject,':html'=>$html,':text'=>trim((string)($_POST['text_template']??''))?:null,':scheduled'=>$schedule,':batch'=>$batch];
                if($id)$p[':id']=$id;else$p[':created']=(int)$currentUser['id'];$s->execute($p);if(!$id)$id=(int)$pdo->lastInsertId();campaign_admin_redirect($id,'Campaign saved. Live approval was reset.');
            }
        } elseif($id>0&&$action==='snapshot'){$result=emailCampaignSnapshotRecipients($pdo,$id);campaign_admin_redirect($id,$result['count'].' unique recipients prepared; '.$result['skipped'].' invalid or non-consenting records skipped.');}
        elseif($id>0&&$action==='send_test'){
            $to=trim((string)($_POST['test_email']??''));$campaign=campaign_admin_row($pdo,$id);
            if(!filter_var($to,FILTER_VALIDATE_EMAIL))$alerts[]=['type'=>'danger','message'=>'Enter a valid test email address.'];
            elseif($campaign){$settings=getSiteSettings($pdo);$merge=array_merge(emailCampaignEventMerge($pdo,(int)($campaign['event_id']??0),emailCampaignBaseUrl($settings)),['campaign_name'=>$campaign['name'],'first_name'=>(string)($currentUser['first_name']??'Test'),'last_name'=>(string)($currentUser['last_name']??''),'full_name'=>trim((string)($currentUser['first_name']??'').' '.(string)($currentUser['last_name']??'')),'email'=>$to,'member_number'=>'TEST','membership_year'=>(string)($campaign['membership_year']??date('Y')),'current_date'=>emailCampaignLocalNow()->format('j F Y'),'membership_url'=>emailCampaignBaseUrl($settings).'/memberships','logbook_url'=>emailCampaignBaseUrl($settings).'/logbooks','message'=>'This is test content.']);$fake=['merge_json'=>json_encode($merge),'tracking_token'=>'test','unsubscribe_token'=>'test'];$payload=emailCampaignRenderRecipient($campaign,$fake,$settings);$emailSettings=getEmailSettings($pdo);$ok=send_logged_email($pdo,$to,subject_with_prefix($emailSettings,$payload['subject']),wrap_user_email_html($settings,$emailSettings,$payload['html'],$payload['after_footer_html']),wrap_user_email_text($settings,$emailSettings,$payload['text'],$payload['after_footer_text']),['kind'=>'campaign_test','campaign_id'=>$id]);$alerts[]=['type'=>$ok?'success':'warning','message'=>$ok?'Test email sent.':'Test email was not sent. Check the email log and delivery safety settings.'];}
        } elseif($id>0&&$action==='send_limited_test'){
            $campaign=campaign_admin_row($pdo,$id);
            if(!$campaign)$alerts[]=['type'=>'danger','message'=>'Campaign not found.'];
            else{$result=campaign_admin_send_limited_test($pdo,$campaign,max(0,(int)($_POST['limited_test_user_id']??0)));$alerts[]=['type'=>$result['ok']?'success':'warning','message'=>$result['message']];}
        } elseif($id>0&&$action==='schedule'){
            $campaign=campaign_admin_row($pdo,$id);$count=$campaign?(int)$campaign['recipient_count']:0;
            if($count<=0)$alerts[]=['type'=>'danger','message'=>'Prepare the recipient snapshot before scheduling.'];
            elseif($roleKey!=='superadmin')$alerts[]=['type'=>'danger','message'=>'Only a Superadmin can approve a live campaign.'];
            else{$scheduled=trim((string)($campaign['scheduled_at']??''))?:emailCampaignLocalNow()->format('Y-m-d H:i:s');$s=$pdo->prepare("UPDATE email_campaigns SET status='scheduled',scheduled_at=:scheduled,live_send_approved=1,approved_by_user_id=:user,approved_at=NOW() WHERE id=:id");$s->execute([':scheduled'=>$scheduled,':user'=>(int)$currentUser['id'],':id'=>$id]);campaign_admin_redirect($id,'Campaign approved and scheduled. The global campaign live-send lock still applies.');}
        }
    }
}

$templates=$pdo->query('SELECT * FROM email_campaign_templates WHERE is_active=1 ORDER BY name')->fetchAll()?:[];
$events=$pdo->query("SELECT id,title,event_date FROM events WHERE event_date>=DATE_SUB(CURDATE(),INTERVAL 3 MONTH) ORDER BY event_date DESC")->fetchAll()?:[];
if($view==='new'&&isset($_GET['template'])){$key=(string)$_GET['template'];$s=$pdo->prepare('SELECT * FROM email_campaign_templates WHERE template_key=:key LIMIT 1');$s->execute([':key'=>$key]);$template=$s->fetch()?:null;}else$template=null;

if($view==='template_select'){
    admin_layout_start('Choose Campaign Template','email_campaigns');?>
    <div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Choose a template</h5><a class="btn btn-outline-secondary" href="campaigns.php">Back</a></div>
    <div class="card-soft p-4"><div class="list-group list-group-flush"><?php foreach($templates as $templateRow): ?><a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="campaigns.php?view=new&amp;template=<?php echo h((string)$templateRow['template_key']); ?>"><span><strong><?php echo h((string)$templateRow['name']); ?></strong><span class="d-block small text-muted"><?php echo h(ucwords(str_replace('_',' ',(string)$templateRow['category']))); ?></span></span><span class="btn btn-sm btn-outline-success">Use template</span></a><?php endforeach; ?></div></div>
    <?php admin_layout_end();exit;
}

if($view==='templates'){
    $allTemplates=$pdo->query('SELECT * FROM email_campaign_templates ORDER BY name')->fetchAll()?:[];admin_layout_start('Campaign Templates','email_campaigns');?>
    <div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Email campaigns</div><h5 class="mb-0">Campaign templates</h5></div><div class="d-flex gap-2"><a class="btn btn-success" href="campaigns.php?view=template_edit">New template</a><a class="btn btn-outline-secondary" href="campaigns.php">Back</a></div></div>
    <div class="card-soft p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Template</th><th>Structure</th><th>Category</th><th>Audience</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($allTemplates as $templateRow): ?><tr><td><strong><?php echo h((string)$templateRow['name']); ?></strong><div class="small text-muted"><?php echo h((string)$templateRow['template_key']); ?></div></td><td><?php echo h(ucwords(str_replace('_',' ',(string)$templateRow['renderer_key']))); ?></td><td><?php echo h(ucwords(str_replace('_',' ',(string)$templateRow['category']))); ?></td><td><?php echo h(emailCampaignPresets()[$templateRow['audience_preset']]??(string)$templateRow['audience_preset']); ?></td><td><?php echo !empty($templateRow['is_active'])?'Active':'Inactive'; ?></td><td><a class="btn btn-sm btn-outline-secondary" href="campaigns.php?view=template_edit&amp;template_id=<?php echo (int)$templateRow['id']; ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></div>
    <?php admin_layout_end();exit;
}

if($view==='template_edit'){
    $templateId=max(0,(int)($_GET['template_id']??$_POST['template_id']??0));$templateRow=null;if($templateId){$s=$pdo->prepare('SELECT * FROM email_campaign_templates WHERE id=:id LIMIT 1');$s->execute([':id'=>$templateId]);$templateRow=$s->fetch()?:null;}
    $templateRow=$templateRow?:['template_key'=>'','name'=>'','renderer_key'=>'freeform','category'=>'general','audience_preset'=>'all_users','subject_template'=>'','intro_html'=>'','outro_html'=>'','html_template'=>'','text_template'=>'','is_active'=>1];admin_layout_start($templateId?'Edit Campaign Template':'New Campaign Template','email_campaigns');?>
    <div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Campaign templates</div><h5 class="mb-0"><?php echo h((string)$templateRow['name']?:'New template'); ?></h5></div><a class="btn btn-outline-secondary" href="campaigns.php?view=templates">Back</a></div>
    <form method="post" class="card-soft p-4"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="save_template"><input type="hidden" name="template_id" value="<?php echo $templateId; ?>"><div class="row g-3">
      <div class="col-md-8"><label class="form-label">Template name</label><input class="form-control" name="name" value="<?php echo h((string)$templateRow['name']); ?>" required></div><div class="col-md-4"><label class="form-label">Template key</label><input class="form-control" name="template_key" value="<?php echo h((string)$templateRow['template_key']); ?>" required></div>
      <div class="col-md-4"><label class="form-label">Structure</label><select class="form-select" name="renderer_key"><option value="freeform" <?php echo $templateRow['renderer_key']==='freeform'?'selected':''; ?>>Free-form</option><option value="membership_renewal" <?php echo $templateRow['renderer_key']==='membership_renewal'?'selected':''; ?>>Membership Renewal</option></select></div><div class="col-md-4"><label class="form-label">Category</label><select class="form-select" name="category"><?php foreach(['operational'=>'Operational','general'=>'General opt-in','ride_notice'=>'Ride Notice opt-in','renewal_reminder'=>'Renewal Reminders'] as $value=>$label): ?><option value="<?php echo h($value); ?>" <?php echo $templateRow['category']===$value?'selected':''; ?>><?php echo h($label); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Default audience</label><select class="form-select" name="audience_preset"><?php foreach(emailCampaignPresets() as $key=>$label): ?><option value="<?php echo h($key); ?>" <?php echo $templateRow['audience_preset']===$key?'selected':''; ?>><?php echo h($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-12"><label class="form-label">Subject</label><input class="form-control" name="subject_template" value="<?php echo h((string)$templateRow['subject_template']); ?>" required></div>
      <div class="col-12"><label class="form-label">Opening text</label><textarea class="form-control wysiwyg-field" rows="6" name="intro_html"><?php echo h((string)$templateRow['intro_html']); ?></textarea></div><div class="col-12"><label class="form-label">Closing text</label><textarea class="form-control wysiwyg-field" rows="6" name="outro_html"><?php echo h((string)$templateRow['outro_html']); ?></textarea></div>
      <div class="col-12"><label class="form-label">Free-form HTML message</label><textarea class="form-control wysiwyg-field" rows="10" name="html_template"><?php echo h((string)$templateRow['html_template']); ?></textarea><div class="form-text">Used by Free-form templates. Structured templates use the opening and closing text around their system block.</div></div><div class="col-12"><label class="form-label">Free-form plain text</label><textarea class="form-control" rows="5" name="text_template"><?php echo h((string)$templateRow['text_template']); ?></textarea></div>
      <div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" id="templateActive" name="is_active" value="1" <?php echo !empty($templateRow['is_active'])?'checked':''; ?>><label class="form-check-label" for="templateActive">Template active</label></div></div><div class="col-12"><button class="btn btn-success">Save template</button></div>
    </div></form><?php render_tinymce_bootstrap(); ?><script>if(window.tinymce)tinymce.init(window.ildraTinyMceConfig({selector:'textarea.wysiwyg-field'}));</script>
    <?php admin_layout_end();exit;
}

if($view==='edit'||$view==='new'){
    $campaign=$id?campaign_admin_row($pdo,$id):null;
    $campaign=$campaign?:['name'=>$template['name']??'','category'=>$template['category']??'general','template_id'=>$template['id']??0,'renderer_key'=>$template['renderer_key']??'freeform','intro_html'=>$template['intro_html']??'','outro_html'=>$template['outro_html']??'','audience_preset'=>$template['audience_preset']??'all_users','event_id'=>0,'membership_year'=>date('Y'),'address_strategy'=>'person_first','subject_template'=>$template['subject_template']??'','html_template'=>$template['html_template']??'','text_template'=>$template['text_template']??'','scheduled_at'=>'','batch_size'=>(int)(getSiteSettings($pdo)['campaign_default_batch_size']??25),'status'=>'draft','recipient_count'=>0,'sent_count'=>0,'failed_count'=>0,'opened_count'=>0,'live_send_approved'=>0];
    $campaignEmailSettings=getEmailSettings($pdo);$campaignProvider=(string)($campaignEmailSettings['email_provider']??'smtp');$campaignTransportLabel=$campaignProvider==='smtp'?'SMTP via '.(string)($campaignEmailSettings['email_smtp_host']??'not configured').':'.(int)($campaignEmailSettings['email_smtp_port']??587):'PHP mail()';
    $limitedTestUsers=$pdo->query("SELECT u.id,u.email,u.first_name,u.last_name,r.name role FROM users u JOIN roles r ON r.id=u.role_id WHERE LOWER(r.name) IN ('admin','superadmin') AND u.email<>'' ORDER BY FIELD(LOWER(r.name),'superadmin','admin'),u.first_name,u.last_name,u.email")->fetchAll()?:[];
    admin_layout_start($id?'Edit Campaign':'New Campaign','email_campaigns');?>
    <div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Email campaigns</div><h5 class="mb-0"><?php echo h((string)$campaign['name']?:'New campaign'); ?></h5></div><a class="btn btn-outline-secondary" href="campaigns.php">Back</a></div>
    <?php if($id): ?><div class="alert <?php echo !empty($campaign['live_send_approved'])?'alert-warning':'alert-secondary'; ?> py-2">Status: <strong><?php echo h((string)$campaign['status']); ?></strong> · Recipients: <?php echo (int)$campaign['recipient_count']; ?> · Sent: <?php echo (int)$campaign['sent_count']; ?> · Failed: <?php echo (int)$campaign['failed_count']; ?> · Opened: <?php echo (int)$campaign['opened_count']; ?><?php if(empty($campaign['live_send_approved'])): ?> · Live sending not approved<?php endif; ?></div><?php endif; ?>
    <form method="post" class="card-soft p-4 mb-4"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="template_id" value="<?php echo (int)($campaign['template_id']??0); ?>"><input type="hidden" name="renderer_key" value="<?php echo h((string)($campaign['renderer_key']??'freeform')); ?>">
      <div class="row g-3"><div class="col-md-8"><label class="form-label">Campaign name</label><input class="form-control" name="name" value="<?php echo h((string)$campaign['name']); ?>" required></div><div class="col-md-4"><label class="form-label">Category</label><select class="form-select" name="category"><option value="operational" <?php echo $campaign['category']==='operational'?'selected':''; ?>>Operational</option><option value="general" <?php echo $campaign['category']==='general'?'selected':''; ?>>General opt-in</option><option value="ride_notice" <?php echo $campaign['category']==='ride_notice'?'selected':''; ?>>Ride Notice opt-in</option><option value="renewal_reminder" <?php echo $campaign['category']==='renewal_reminder'?'selected':''; ?>>Renewal Reminders</option></select></div>
      <div class="col-md-4"><label class="form-label">Audience</label><select class="form-select" name="audience_preset"><?php foreach(emailCampaignPresets() as $key=>$label): ?><option value="<?php echo h($key); ?>" <?php echo $campaign['audience_preset']===$key?'selected':''; ?>><?php echo h($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-md-4"><label class="form-label">Event where applicable</label><select class="form-select" name="event_id"><option value="0">None</option><?php foreach($events as $event): ?><option value="<?php echo (int)$event['id']; ?>" <?php echo (int)$campaign['event_id']===(int)$event['id']?'selected':''; ?>><?php echo h(format_display_date($event['event_date'],'').' · '.$event['title']); ?></option><?php endforeach; ?></select></div>
      <div class="col-md-2"><label class="form-label">Membership year</label><input class="form-control" type="number" min="2000" max="2100" step="1" name="membership_year" value="<?php echo (int)$campaign['membership_year']; ?>"></div><div class="col-md-2"><label class="form-label">Batch size</label><input class="form-control" type="number" min="1" max="500" step="1" name="batch_size" value="<?php echo (int)$campaign['batch_size']; ?>"></div>
      <div class="col-md-4"><label class="form-label">Email address choice</label><select class="form-select" name="address_strategy"><option value="person_first" <?php echo $campaign['address_strategy']==='person_first'?'selected':''; ?>>Person first, account fallback</option><option value="account_only" <?php echo $campaign['address_strategy']==='account_only'?'selected':''; ?>>Account only</option><option value="person_only" <?php echo $campaign['address_strategy']==='person_only'?'selected':''; ?>>Person only</option></select></div><div class="col-md-4"><label class="form-label">Schedule (UK local time)</label><input class="form-control" type="datetime-local" name="scheduled_at" value="<?php echo h($campaign['scheduled_at']?date('Y-m-d\TH:i',strtotime((string)$campaign['scheduled_at'])):''); ?>" step="900"></div>
      <div class="col-12"><label class="form-label">Subject</label><input class="form-control" name="subject_template" value="<?php echo h((string)$campaign['subject_template']); ?>" required></div>
      <?php if(($campaign['renderer_key']??'freeform')==='membership_renewal'): ?><div class="col-12"><div class="alert alert-secondary py-2 mb-0">Membership Renewal structure: greeting, membership details and renewal button are generated by the system.</div></div><div class="col-12"><label class="form-label">Opening text</label><textarea class="form-control wysiwyg-field" rows="7" name="intro_html"><?php echo h((string)($campaign['intro_html']??'')); ?></textarea></div><div class="col-12"><label class="form-label">Closing text</label><textarea class="form-control wysiwyg-field" rows="7" name="outro_html"><?php echo h((string)($campaign['outro_html']??'')); ?></textarea></div><input type="hidden" name="html_template" value="<?php echo h((string)$campaign['html_template']); ?>"><input type="hidden" name="text_template" value="<?php echo h((string)$campaign['text_template']); ?>"><?php else: ?><input type="hidden" name="intro_html" value=""><input type="hidden" name="outro_html" value=""><div class="col-12"><label class="form-label">HTML message</label><textarea class="form-control wysiwyg-field" rows="12" name="html_template"><?php echo h((string)$campaign['html_template']); ?></textarea></div><div class="col-12"><label class="form-label">Plain-text message</label><textarea class="form-control" rows="7" name="text_template"><?php echo h((string)$campaign['text_template']); ?></textarea></div><?php endif; ?>
      <div class="col-12 small text-muted">Merge fields: {{first_name}}, {{full_name}}, {{email}}, {{member_number}}, {{membership_year}}, {{event_title}}, {{event_date}}, {{event_venue}}, {{entry_close_date}}, {{event_url}}, {{ride_notes_url}}, {{membership_url}}, {{logbook_url}}, {{current_date}}.</div><div class="col-12"><button class="btn btn-success">Save campaign</button></div></div></form>
    <?php if($id&&in_array((string)$campaign['status'],['draft','paused','scheduled'],true)): ?><div class="row g-3"><div class="col-md-4"><form method="post" class="card-soft p-3 h-100"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="snapshot"><input type="hidden" name="id" value="<?php echo $id; ?>"><h6>1. Prepare recipients</h6><p class="small text-muted">Creates a deduplicated, consent-checked snapshot.</p><button class="btn btn-outline-success">Prepare snapshot</button></form></div><div class="col-md-4"><form method="post" class="card-soft p-3 h-100"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="send_test"><input type="hidden" name="id" value="<?php echo $id; ?>"><h6>2. Test</h6><div class="small text-muted mb-2"><?php echo h($campaignTransportLabel); ?></div><input class="form-control mb-2" type="email" name="test_email" value="<?php echo h((string)($currentUser['email']??'')); ?>" required><button class="btn btn-outline-primary">Send test</button></form></div><div class="col-md-4"><form method="post" class="card-soft p-3 h-100"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="schedule"><input type="hidden" name="id" value="<?php echo $id; ?>"><h6>3. Approve</h6><p class="small text-muted">Superadmin only. Campaign delivery also requires the global live-send switch.</p><button class="btn btn-warning" <?php echo $roleKey!=='superadmin'?'disabled':''; ?>>Approve and schedule</button></form></div></div>
    <form method="post" class="card-soft p-3 mt-3"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="send_limited_test"><input type="hidden" name="id" value="<?php echo $id; ?>"><div class="row g-2 align-items-end"><div class="col-md-8"><h6>Send limited test</h6><div class="small text-muted mb-2">Uses the selected administrator's real merge fields, open tracking and unsubscribe link.</div><select class="form-select" name="limited_test_user_id" required><option value="">Choose an administrator</option><?php foreach($limitedTestUsers as $testUser): $testName=trim((string)$testUser['first_name'].' '.(string)$testUser['last_name']); ?><option value="<?php echo (int)$testUser['id']; ?>"><?php echo h(($testName!==''?$testName.' · ':'').$testUser['email'].' · '.ucfirst((string)$testUser['role'])); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><button class="btn btn-outline-primary w-100">Send limited test</button></div></div></form><?php endif; ?>
    <?php if($id): $recipientStmt=$pdo->prepare('SELECT * FROM email_campaign_recipients WHERE campaign_id=:id ORDER BY id DESC LIMIT 200');$recipientStmt->execute([':id'=>$id]);$recipientRows=$recipientStmt->fetchAll()?:[]; ?>
    <div class="card-soft p-4 mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="mb-0">Recipient report</h6><span class="small text-muted">Open counts are approximate</span></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Recipient</th><th>Status</th><th>Sent</th><th>Opened</th><th>Email log</th></tr></thead><tbody><?php if(!$recipientRows): ?><tr><td colspan="5" class="text-muted">Prepare a recipient snapshot to populate this report.</td></tr><?php endif; ?><?php foreach($recipientRows as $recipientRow): ?><tr><td><?php echo h(trim((string)$recipientRow['first_name'].' '.(string)$recipientRow['last_name'])); ?><div class="small text-muted"><?php echo h((string)$recipientRow['email']); ?></div></td><td><?php echo h(ucfirst((string)$recipientRow['status'])); ?><?php if($recipientRow['error_message']): ?><div class="small text-danger"><?php echo h((string)$recipientRow['error_message']); ?></div><?php endif; ?></td><td><?php echo $recipientRow['sent_at']?h(date('d M Y H:i',strtotime((string)$recipientRow['sent_at']))):'—'; ?></td><td><?php echo (int)$recipientRow['open_count']; ?><?php if($recipientRow['first_opened_at']): ?><div class="small text-muted">First <?php echo h(date('d M Y H:i',strtotime((string)$recipientRow['first_opened_at']))); ?></div><?php endif; ?></td><td><?php if($recipientRow['email_log_id']): ?><a href="email_view.php?id=<?php echo (int)$recipientRow['email_log_id']; ?>">#<?php echo (int)$recipientRow['email_log_id']; ?></a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
    <?php render_tinymce_bootstrap(); ?><script>if(window.tinymce)tinymce.init(window.ildraTinyMceConfig({selector:'textarea.wysiwyg-field'}));</script><?php admin_layout_end();exit;
}

$rows=$pdo->query('SELECT c.*,e.title event_title FROM email_campaigns c LEFT JOIN events e ON e.id=c.event_id ORDER BY c.id DESC')->fetchAll()?:[];
admin_layout_start('Email Campaigns','email_campaigns');?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><div class="text-muted">Email campaigns</div><div class="small text-muted">Templates, audiences, scheduling and delivery reports</div></div><div class="dropdown"><button class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown">New campaign</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="campaigns.php?view=new">Blank campaign</a></li><li><a class="dropdown-item" href="campaigns.php?view=template_select">From template</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="campaigns.php?view=templates">Manage templates</a></li></ul></div></div>
<div class="card-soft p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Campaign</th><th>Audience</th><th>Status</th><th>Scheduled (UK)</th><th>Delivery</th><th></th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="6" class="text-muted">No campaigns yet.</td></tr><?php endif; ?><?php foreach($rows as $row): ?><tr><td><strong><?php echo h((string)$row['name']); ?></strong><?php if($row['event_title']): ?><div class="small text-muted"><?php echo h((string)$row['event_title']); ?></div><?php endif; ?></td><td><?php echo h(emailCampaignPresets()[$row['audience_preset']]??(string)$row['audience_preset']); ?></td><td><?php echo h(ucfirst((string)$row['status'])); ?></td><td><?php echo $row['scheduled_at']?h(date('d M Y H:i',strtotime((string)$row['scheduled_at']))):'—'; ?></td><td><?php echo (int)$row['sent_count']; ?>/<?php echo (int)$row['recipient_count']; ?> sent · <?php echo (int)$row['opened_count']; ?> opened</td><td><a class="btn btn-sm btn-outline-secondary" href="campaigns.php?view=edit&amp;id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php admin_layout_end();
