<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
require_once __DIR__ . '/table_sort.php';
if(!in_array(strtolower((string)($currentUser['role']??'')),['superadmin','developer'],true)){http_response_code(403);exit('Coupon management is restricted to super administrators.');}
ensureCouponTables($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=(string)($_POST['action']??'');$id=(int)($_POST['coupon_id']??0);
    if(($action==='cancel'||$action==='enable')&&$id){$status=$action==='enable'?'active':'cancelled';$pdo->prepare('UPDATE coupons SET status=:status,updated_at=NOW() WHERE id=:id')->execute([':status'=>$status,':id'=>$id]);coupon_log($pdo,$id,(int)$currentUser['id'],$action==='enable'?'enabled':'cancelled');$_SESSION['flash_success']=$action==='enable'?'Coupon enabled.':'Coupon cancelled.';header('Location: coupons.php');exit;}
    if($action==='email'){$email=trim((string)($_POST['recipient_email']??''));$stmt=$pdo->prepare('SELECT c.*,e.title event_title FROM coupons c LEFT JOIN events e ON e.id=c.event_id WHERE c.id=:id');$stmt->execute([':id'=>$id]);$coupon=$stmt->fetch();if(!$coupon||!filter_var($email,FILTER_VALIDATE_EMAIL))$alerts[]=['type'=>'danger','message'=>'Choose a valid coupon and recipient email.'];else{$settings=getSiteSettings($pdo);$link=rtrim(email_public_asset_url('/',$settings),'/').'/basket?coupon='.rawurlencode((string)$coupon['code']);$inner='<h2>'.h((string)$coupon['title']).'</h2><p>You have received an ILDRA coupon worth <strong>'.h(format_price($coupon['amount'])).'</strong>.</p><p style="font-size:22px;font-weight:bold;letter-spacing:.08em">'.h((string)$coupon['code']).'</p><p>Valid from '.h(format_display_datetime($coupon['valid_from'])).' to '.h(format_display_datetime($coupon['valid_until'])).'.</p><p>Use: '.h((string)($coupon['event_title']?:'Any eligible ILDRA purchase')).'.</p>'.(string)($coupon['message_html']??'').'<p><a href="'.h($link).'">Open your basket and apply this coupon</a></p>';$ok=send_logged_email($pdo,$email,'Your ILDRA coupon: '.(string)$coupon['code'],wrap_user_email_html($settings,getEmailSettings($pdo),$inner),strip_tags($inner),['type'=>'coupon','send_type'=>1,'coupon_id'=>$id,'coupon_code'=>$coupon['code']]);coupon_log($pdo,$id,(int)$currentUser['id'],$ok?'emailed':'email_failed',$email);if($ok){$pdo->prepare('UPDATE coupons SET recipient_email=:email,updated_at=NOW() WHERE id=:id')->execute([':email'=>$email,':id'=>$id]);$_SESSION['flash_success']='Coupon emailed.';header('Location: coupons.php');exit;}$alerts[]=['type'=>'warning','message'=>'Coupon email could not be sent. Check Email logs.'];}}
}
$rows=$pdo->query('SELECT c.*,e.title event_title FROM coupons c LEFT JOIN events e ON e.id=c.event_id ORDER BY c.created_at DESC LIMIT 1000')->fetchAll()?:[];
$columns=['code'=>['label'=>'Code / wording','sortable'=>true,'filter'=>'text','placeholder'=>'Code, wording, recipient or event','value'=>static fn(array$c):string=>(string)$c['code'].' '.(string)$c['title'].' '.(string)($c['recipient_email']??'').' '.(string)($c['event_title']??'')],'type'=>['label'=>'Type','sortable'=>true,'filter'=>'select','options'=>['manual'=>'Manual','ride_helper'=>'Ride Helper','marketing'=>'Marketing'],'value'=>static fn(array$c):string=>(string)$c['coupon_type']],'value'=>['label'=>'Value','sortable'=>true,'compare'=>'number','value'=>static fn(array$c):string=>(string)$c['amount']],'valid'=>['label'=>'Valid until','sortable'=>true,'filter'=>'date','value'=>static fn(array$c):string=>(string)$c['valid_until']],'uses'=>['label'=>'Uses / scope','sortable'=>true,'compare'=>'number','value'=>static fn(array$c):string=>(string)$c['use_count']],'status'=>['label'=>'Status','sortable'=>true,'filter'=>'select','options'=>['active'=>'Active','cancelled'=>'Cancelled','expired'=>'Expired'],'value'=>static fn(array$c):string=>(string)$c['status']]];
$table=admin_table_prepare($rows,$columns,'valid','desc');$coupons=$table['rows'];$filters=$table['filters'];$sortKey=$table['sort_key'];$sortDir=$table['sort_dir'];$returnTo='coupons.php'.($_GET?('?'.http_build_query($_GET)):'' );
admin_layout_start('Coupons','coupons');
?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Super administrator</div><h5 class="mb-0">Coupon management</h5></div><a class="btn btn-success" href="coupon_edit.php?return_to=<?php echo rawurlencode($returnTo); ?>">Add new coupon</a></div>
<div class="card-soft p-3"><form method="get" id="coupon-filter-form" class="text-end mb-2"><button class="btn btn-sm btn-outline-secondary">Filter</button> <a class="btn btn-sm btn-link" href="coupons.php">Clear</a></form><?php echo admin_table_record_count($table,'coupon','coupons'); ?><div class="table-responsive"><table class="table align-middle"><thead><tr><?php foreach($columns as$key=>$column):?><th><?php echo admin_table_heading($key,$column,$sortKey,$sortDir);?></th><?php endforeach;?><th class="text-end">Actions</th></tr><tr class="admin-table-filter-row"><?php foreach($columns as$key=>$column):?><th><?php echo admin_table_filter($key,$column,$filters);?></th><?php endforeach;?><th></th></tr></thead><tbody><?php foreach($coupons as$c):?><tr><td><strong><?php echo h($c['code']);?></strong><div class="small text-muted"><?php echo h($c['title']);?></div></td><td><?php echo h(str_replace('_',' ',$c['coupon_type']));?></td><td><?php echo h(format_price($c['amount']));?></td><td><?php echo h(format_display_datetime($c['valid_until']));?></td><td><?php echo(int)$c['use_count'];?> / <?php echo(int)$c['usage_limit'];?><div class="small text-muted"><?php echo h($c['event_title']?:'Eligible purchases');?></div></td><td><?php echo h($c['status']);?></td><td class="text-nowrap text-end"><a class="btn btn-sm btn-outline-primary mb-1" href="coupon_edit.php?id=<?php echo(int)$c['id'];?>&return_to=<?php echo rawurlencode($returnTo); ?>">Edit</a><a class="btn btn-sm btn-outline-secondary mb-1" target="_blank" href="coupon_print.php?id=<?php echo(int)$c['id'];?>">Print / PDF</a><?php if($c['status']==='active'):?><form method="post" class="mb-1"><input type="hidden" name="action" value="email"><input type="hidden" name="coupon_id" value="<?php echo(int)$c['id'];?>"><input class="form-control form-control-sm mb-1" required type="email" name="recipient_email" value="<?php echo h((string)($c['recipient_email']??''));?>" placeholder="Email recipient"><button class="btn btn-sm btn-outline-success">Email</button></form><form method="post"><input type="hidden" name="action" value="cancel"><input type="hidden" name="coupon_id" value="<?php echo(int)$c['id'];?>"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Cancel this coupon?')">Cancel</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$coupons):?><tr><td colspan="7" class="text-muted">No coupons match the current filters.</td></tr><?php endif;?></tbody></table></div><?php echo admin_table_pagination($table); ?></div>
<script>document.querySelectorAll('tbody tr').forEach(row=>{const cells=row.querySelectorAll('td');if(cells.length<7||cells[5].textContent.trim()!=='cancelled')return;const id=(row.querySelector('a[href*="coupon_edit.php?id="]')||{}).href?.match(/[?&]id=(\d+)/)?.[1];if(!id)return;const form=document.createElement('form');form.method='post';form.className='d-inline';form.innerHTML='<input type="hidden" name="action" value="enable"><?php echo csrf_input(); ?><input type="hidden" name="coupon_id" value="'+id+'"><button class="btn btn-sm btn-outline-success mb-1">Enable</button>';cells[6].prepend(form);});</script>
<?php admin_layout_end();
