<?php
declare(strict_types=1);
require __DIR__.'/_bootstrap.php';
if(!in_array(strtolower((string)($currentUser['role']??'')),['superadmin','admin'],true)){header('Location:index.php');exit;}
$elementId=max(0,(int)($_GET['element_id']??$_POST['element_id']??0));$element=fetchPageContentElement($pdo,$elementId);$page=$element?fetchPageById($pdo,(int)$element['page_id']):null;
if(!$element||!$page){$_SESSION['flash_alerts']=[['type'=>'danger','message'=>'Content section not found.']];header('Location:pages.php');exit;}
$batch=mediaBatchGetOrCreate($pdo,'content_element_images','page_content_element',$elementId,'Images for '.$element['name'],'page-elements');
if($_SERVER['REQUEST_METHOD']==='POST'){$action=(string)($_POST['action']??'upload');if($action==='upload'){$errors=[];$count=mediaBatchUpload($pdo,$batch,$_FILES['images']??[],['original'=>null,'lg'=>1200,'md'=>600,'sm'=>300,'xs'=>150],$errors);foreach($errors as$error)$alerts[]=['type'=>'danger','message'=>$error];if($count){$_SESSION['flash_success']=$count.($count===1?' image':' images').' uploaded.';header('Location:element_images.php?element_id='.$elementId);exit;}}else{$allowed=array_column(mediaBatchImages($pdo,(int)$batch['id'],true),null,'id');foreach((array)($_POST['image']??[])as$id=>$v){$id=(int)$id;if(!isset($allowed[$id]))continue;$pdo->prepare('UPDATE media_batch_images SET title=:title,alt_text=:alt,caption=:caption,display_order=:ord,archived=:archived,updated_at=NOW() WHERE id=:id AND batch_id=:batch')->execute([':title'=>trim((string)($v['title']??''))?:null,':alt'=>trim((string)($v['alt_text']??''))?:null,':caption'=>trim((string)($v['caption']??''))?:null,':ord'=>(int)($v['display_order']??100),':archived'=>!empty($v['archived'])?1:0,':id'=>$id,':batch'=>$batch['id']]);}$_SESSION['flash_success']='Section images updated.';header('Location:element_images.php?element_id='.$elementId);exit;}}
$images=mediaBatchImages($pdo,(int)$batch['id'],true);admin_layout_start('Content Section Images','pages');?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted"><?php echo h($page['title']); ?></div><h5 class="mb-0">Images: <?php echo h($element['name']); ?></h5></div><a class="btn btn-outline-secondary" href="page_elements.php?page_id=<?php echo (int)$page['id']; ?>">Back to Sections</a></div>
<div class="card-soft p-4 mb-4"><form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="upload"><input type="hidden" name="element_id" value="<?php echo $elementId; ?>"><label id="drop-zone" class="d-block border border-2 rounded-3 p-4 text-center bg-light" style="cursor:pointer"><input class="visually-hidden" id="files" type="file" name="images[]" accept="image/jpeg,image/png,image/gif,image/webp" multiple required><strong class="fs-5 d-block">Drop images here</strong><span class="text-muted">or click to browse</span><span id="summary" class="small text-success d-block"></span></label><button class="btn btn-success mt-3">Upload Images</button></form></div>
<div class="card-soft p-3"><form method="post"><input type="hidden" name="action" value="save"><input type="hidden" name="element_id" value="<?php echo $elementId; ?>"><table class="table align-middle"><thead><tr><th>Preview</th><th>Order</th><th>Details</th><th>State</th></tr></thead><tbody><?php foreach($images as$i=>$image): ?><tr><td><img src="<?php echo h(mediaBatchImageUrl($batch,$image,'sm')); ?>" style="width:180px;max-height:100px;object-fit:cover" class="rounded"><?php if($i===0&&!$image['archived']): ?><span class="badge bg-success">Main</span><?php endif; ?></td><td><input class="form-control" style="width:90px" type="number" name="image[<?php echo (int)$image['id']; ?>][display_order]" value="<?php echo (int)$image['display_order']; ?>"></td><td><input class="form-control form-control-sm mb-1" name="image[<?php echo (int)$image['id']; ?>][title]" value="<?php echo h($image['title']??''); ?>" placeholder="Title"><input class="form-control form-control-sm mb-1" name="image[<?php echo (int)$image['id']; ?>][alt_text]" value="<?php echo h($image['alt_text']??''); ?>" placeholder="Alt text"><textarea class="form-control form-control-sm" name="image[<?php echo (int)$image['id']; ?>][caption]" placeholder="Caption"><?php echo h($image['caption']??''); ?></textarea></td><td><label><input type="checkbox" name="image[<?php echo (int)$image['id']; ?>][archived]" value="1" <?php echo $image['archived']?'checked':''; ?>> Archived</label></td></tr><?php endforeach; ?><?php if(!$images): ?><tr><td colspan="4">No images yet.</td></tr><?php endif; ?></tbody></table><?php if($images): ?><button class="btn btn-success">Save Images</button><?php endif; ?></form></div>
<script>(function(){const z=document.getElementById('drop-zone'),f=document.getElementById('files'),s=document.getElementById('summary');function show(){const a=Array.from(f.files||[]);s.textContent=a.length+' image(s) selected';}['dragover','dragenter'].forEach(t=>z.addEventListener(t,e=>e.preventDefault()));z.addEventListener('drop',e=>{e.preventDefault();f.files=e.dataTransfer.files;show();});f.addEventListener('change',show);})();</script><?php admin_layout_end();
