<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
ensureExternalRecognitionTables($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=(string)($_POST['action']??'');
    if($action==='save_organisation'&&saveRecognisedOrganisation($pdo,$_POST,$alerts)){$_SESSION['flash_success']='Organisation saved.';header('Location: external_recognition.php');exit;}
    if($action==='review'){$id=(int)($_POST['application_id']??0);$status=(string)($_POST['status']??'');if($id>0&&reviewExternalRecognition($pdo,$id,$status,(int)$currentUser['id'],(string)($_POST['admin_notes']??''))){$_SESSION['flash_success']='Recognition application updated.';header('Location: external_recognition.php');exit;}}
    if($action==='request_verification'){$applicationId=(int)($_POST['application_id']??0);$organisationId=(int)($_POST['organisation_id']??0);if($applicationId>0&&$organisationId>0){$link=$pdo->prepare('UPDATE external_recognition_applications a JOIN recognised_organisations o ON o.id=:org AND o.is_active=1 SET a.organisation_id=o.id,a.organisation_country_code=o.country_code WHERE a.id=:id');$link->execute([':org'=>$organisationId,':id'=>$applicationId]);}$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$baseUrl=$scheme.'://'.($_SERVER['HTTP_HOST']??'').($siteBase??'');if(requestExternalRecognitionVerification($pdo,$applicationId,(int)$currentUser['id'],$baseUrl,$alerts)){$_SESSION['flash_success']='Verification request sent.';header('Location: external_recognition.php');exit;}}
}
$organisations=fetchRecognisedOrganisations($pdo,false);$applications=fetchExternalRecognitionApplications($pdo);
admin_layout_start('External Recognition','external_recognition');
?>
<div class="d-flex justify-content-between align-items-start mb-3"><div><div class="small text-muted">Visiting riders and horses</div><h5 class="mb-0">External Recognition</h5></div></div>
<div class="alert alert-info">Verified records grant ride eligibility only. They do not create ILDRA membership or an ILDRA horse logbook.</div>
<section class="card-soft p-3 mb-4"><h6>Applications</h6><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Applicant</th><th>For</th><th>Organisation</th><th>Credential</th><th>Expires</th><th>Status</th><th>Review</th></tr></thead><tbody>
<?php foreach($applications as $application): ?><tr><td><?php echo h((string)$application['applicant_email']); ?></td><td><strong><?php echo h((string)($application['person_name']?:$application['horse_name'])); ?></strong><div class="small text-muted text-capitalize"><?php echo h((string)$application['subject_type']); ?></div></td><td><?php echo h((string)($application['organisation_name']?:$application['other_organisation_name'])); ?> [<?php echo h((string)$application['organisation_country_code']); ?>]</td><td><?php echo h((string)$application['credential_number']); ?></td><td><?php echo h(format_display_date($application['valid_until'])); ?></td><td class="text-capitalize"><?php echo h(str_replace('_',' ',(string)$application['status'])); ?></td><td><div class="d-flex gap-2"><form method="post" class="d-flex gap-1"><input type="hidden" name="action" value="request_verification"><input type="hidden" name="application_id" value="<?php echo (int)$application['id']; ?>"><select class="form-select form-select-sm" name="organisation_id" aria-label="Verification organisation"><option value="">Organisation...</option><?php foreach($organisations as $organisation): ?><option value="<?php echo (int)$organisation['id']; ?>" <?php echo (int)$application['organisation_id']===(int)$organisation['id']?'selected':''; ?>><?php echo h((string)$organisation['code']); ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-primary">Request verification</button></form><form method="post" class="d-flex gap-2"><input type="hidden" name="action" value="review"><input type="hidden" name="application_id" value="<?php echo (int)$application['id']; ?>"><select class="form-select form-select-sm" name="status"><option value="verified">Verify</option><option value="rejected">Reject</option><option value="withdrawn">Withdraw</option></select><input class="form-control form-control-sm" name="admin_notes" placeholder="Review note"><button class="btn btn-sm btn-success">Save</button></form></div></td></tr><?php endforeach; ?>
<?php if(!$applications): ?><tr><td colspan="7" class="text-muted">No applications.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="card-soft p-3"><h6>Recognised organisations</h6><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Code</th><th>Name</th><th>Country</th><th>Verification email</th><th>Approved</th><th>Active</th><th></th></tr></thead><tbody>
<?php foreach(array_merge($organisations,[['id'=>0,'code'=>'','name'=>'','country_code'=>'','verification_email'=>'','is_approved'=>1,'is_active'=>1]]) as $organisation): $organisationFormId='organisation-form-'.(int)$organisation['id']; ?>
<tr>
    <td><form method="post" id="<?php echo h($organisationFormId); ?>"><input type="hidden" name="action" value="save_organisation"><input type="hidden" name="organisation_id" value="<?php echo (int)$organisation['id']; ?>"></form><input form="<?php echo h($organisationFormId); ?>" class="form-control form-control-sm" name="code" value="<?php echo h((string)$organisation['code']); ?>" placeholder="EI" required></td>
    <td><input form="<?php echo h($organisationFormId); ?>" class="form-control form-control-sm" name="name" value="<?php echo h((string)$organisation['name']); ?>" placeholder="Organisation name" required></td>
    <td><input form="<?php echo h($organisationFormId); ?>" class="form-control form-control-sm text-uppercase" name="country_code" maxlength="2" value="<?php echo h((string)$organisation['country_code']); ?>" required></td>
    <td><input form="<?php echo h($organisationFormId); ?>" class="form-control form-control-sm" type="email" name="verification_email" value="<?php echo h((string)$organisation['verification_email']); ?>"></td>
    <td><input form="<?php echo h($organisationFormId); ?>" class="form-check-input" type="checkbox" name="is_approved" value="1" <?php echo !empty($organisation['is_approved'])?'checked':''; ?>></td>
    <td><input form="<?php echo h($organisationFormId); ?>" class="form-check-input" type="checkbox" name="is_active" value="1" <?php echo !empty($organisation['is_active'])?'checked':''; ?>></td>
    <td><button form="<?php echo h($organisationFormId); ?>" class="btn btn-sm btn-outline-success"><?php echo (int)$organisation['id']?'Save':'Add'; ?></button></td>
</tr><?php endforeach; ?></tbody></table></div></section>
<?php admin_layout_end(); ?>
