<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
$isAdmin=in_array(strtolower((string)($currentUser['role']??'')),['superadmin','admin'],true);
if(!$isAdmin){header('Location: index.php');exit;}
ensureHelpTables($pdo);
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 $action=(string)($_POST['action']??'');
 if($action==='save_group' && saveHelpGroup($pdo,$_POST,$alerts)){$_SESSION['flash_success']='Help section saved.';header('Location: help.php');exit;}
 if($action==='delete_article'){$stmt=$pdo->prepare('DELETE FROM help_articles WHERE id=:id');$stmt->execute([':id'=>(int)($_POST['id']??0)]);$_SESSION['flash_success']='Help article deleted.';header('Location: help.php');exit;}
}
$groups=fetchHelpGroups($pdo,false);$articles=$pdo->query('SELECT a.*,g.name AS group_name FROM help_articles a LEFT JOIN help_groups g ON g.id=a.group_id ORDER BY a.display_order,a.title')->fetchAll();
$editGroup=null;$gid=(int)($_GET['group']??0);foreach($groups as $g)if((int)$g['id']===$gid)$editGroup=$g;
if(isset($_GET['new_group']))$editGroup=['id'=>0,'name'=>'','description'=>'','path_patterns'=>'','display_order'=>0,'is_active'=>1];
admin_layout_start('Help','help');
?>
<div class="d-flex justify-content-between flex-wrap gap-2 mb-3"><div><div class="small text-muted">Contextual guidance by page and user level</div><h5 class="mb-0">Help</h5></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="account_intros.php">Account Help</a><a class="btn btn-outline-success" href="help.php?new_group=1">Add page group</a><a class="btn btn-success" href="help_edit.php">Add help article</a></div></div>
<?php if($alerts):foreach($alerts as $alert):?><div class="alert alert-<?php echo h($alert['type']); ?>"><?php echo h($alert['message']); ?></div><?php endforeach;endif;?>
<?php if($editGroup):?><div class="card-soft p-4 mb-4"><h6><?php echo $editGroup['id']?'Edit':'Add'; ?> page group</h6><form method="post" class="row g-3"><input type="hidden" name="action" value="save_group"><input type="hidden" name="group_id" value="<?php echo (int)$editGroup['id']; ?>"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" required value="<?php echo h($editGroup['name']); ?>"></div><div class="col-md-6"><label class="form-label">Description</label><input class="form-control" name="description" value="<?php echo h($editGroup['description']); ?>"></div><div class="col-md-8"><label class="form-label">Page URL patterns</label><textarea class="form-control" name="path_patterns" rows="4" required placeholder="/account&#10;/member-login.php&#10;/admin/*.php"><?php echo h($editGroup['path_patterns']); ?></textarea><div class="form-text">One pattern per line. Use * as a wildcard.</div></div><div class="col-md-2"><label class="form-label">Order</label><input class="form-control" type="number" name="display_order" value="<?php echo (int)$editGroup['display_order']; ?>"></div><div class="col-md-2 pt-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_active" id="group-active" <?php echo $editGroup['is_active']?'checked':'';?>><label class="form-check-label" for="group-active">Active</label></div></div><div><button class="btn btn-success">Save group</button> <a class="btn btn-outline-secondary" href="help.php">Cancel</a></div></form></div><?php endif;?>
<div class="card-soft p-3 mb-4"><h6>Page groups</h6><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Name</th><th>URL patterns</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($groups as $g):?><tr><td><?php echo h($g['name']); ?></td><td><small><?php echo nl2br(h($g['path_patterns'])); ?></small></td><td><?php echo $g['is_active']?'Active':'Hidden'; ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="help.php?group=<?php echo (int)$g['id']; ?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card-soft p-3"><h6>Help articles</h6><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Title</th><th>Location</th><th>User levels</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($articles as $a):?><tr><td><?php echo h($a['title']); ?></td><td><?php echo h($a['group_name']?:'Global'); ?></td><td><?php echo (int)$a['min_user_level']; ?>–<?php echo $a['max_user_level']===null?'any':(int)$a['max_user_level']; ?></td><td><?php echo $a['is_published']?'Published':'Draft'; ?></td><td class="text-end"><a class="btn btn-sm btn-outline-success" href="help_edit.php?id=<?php echo (int)$a['id']; ?>">Edit</a> <form method="post" class="d-inline" onsubmit="return confirm('Delete this help article?')"><input type="hidden" name="action" value="delete_article"><input type="hidden" name="id" value="<?php echo (int)$a['id']; ?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach;?><?php if(!$articles):?><tr><td colspan="5" class="text-muted">No help articles yet.</td></tr><?php endif;?></tbody></table></div></div>
<?php admin_layout_end(); ?>
