<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
if (!in_array(strtolower((string)($currentUser['role'] ?? '')), ['superadmin','admin','organiser'], true)) { header('Location:index.php'); exit; }
ensureNewsTables($pdo);
$id=max(0,(int)($_GET['id']??$_POST['id']??0));$article=$id?fetchNewsArticle($pdo,$id):null;
$eventId=max(0,(int)($_GET['event_id']??$_POST['event_id']??($article['event_id']??0)));$type=(($_GET['type']??$_POST['article_type']??($article['article_type']??'news'))==='ride_report')?'ride_report':'news';$event=$eventId?fetchEventById($pdo,$eventId):null;
if(!$event){$eventId=0;if(!$id)$type='news';}
$eventLastDate=$event?(string)($event['end_date']?:($event['event_date']??'')):'';
$canAddRideReport=$eventLastDate!==''&&$eventLastDate<date('Y-m-d');
if(!$id&&$type==='ride_report'&&!$canAddRideReport){$_SESSION['flash_alerts'][]=['type'=>'danger','message'=>'Ride reports can only be added after an event has finished.'];header('Location:events.php?view=future');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    $headline=trim((string)($_POST['headline']??''));$slug=image_upload_slug(trim((string)($_POST['slug']??''))?:$headline);$sub=trim((string)($_POST['subheading']??''));$body=trim((string)($_POST['body_html']??''));$results=$type==='ride_report'?trim((string)($_POST['results_html']??'')):null;$published=!empty($_POST['is_published'])?1:0;
    $date=trim((string)($_POST['publication_date']??''));$time=trim((string)($_POST['publication_time']??''));$at=null;
    if($date!==''){if(DateTimeImmutable::createFromFormat('!Y-m-d',$date)===false||!preg_match('/^(?:[01][0-9]|2[0-3]):(?:00|15|30|45)$/',$time))$alerts[]=['type'=>'danger','message'=>'Choose a valid publication date and a time in 15-minute intervals.'];else $at=$date.' '.$time.':00';}
    if($headline==='')$alerts[]=['type'=>'danger','message'=>'Headline is required.'];if($type==='ride_report'&&!$event)$alerts[]=['type'=>'danger','message'=>'A ride report must be linked to an event.'];if(!$id&&$type==='ride_report'&&!$canAddRideReport)$alerts[]=['type'=>'danger','message'=>'Ride reports can only be added after an event has finished.'];
    if(!$alerts){try{$values=[':type'=>$type,':event'=>$eventId?:null,':headline'=>$headline,':slug'=>$slug,':sub'=>$sub?:null,':body'=>$body?:null,':results'=>$results?:null,':published'=>$published,':at'=>$at];if($id){$values[':id']=$id;$stmt=$pdo->prepare('UPDATE news_articles SET article_type=:type,event_id=:event,headline=:headline,slug=:slug,subheading=:sub,body_html=:body,results_html=:results,is_published=:published,published_at=:at,updated_at=NOW() WHERE id=:id');}else{$stmt=$pdo->prepare('INSERT INTO news_articles(article_type,event_id,headline,slug,subheading,body_html,results_html,is_published,published_at) VALUES(:type,:event,:headline,:slug,:sub,:body,:results,:published,:at)');}$stmt->execute($values);if(!$id)$id=(int)$pdo->lastInsertId();$_SESSION['flash_success']=$type==='ride_report'?'Ride report saved.':'News item saved.';header('Location:news_edit.php?id='.$id);exit;}catch(PDOException $e){$alerts[]=['type'=>'danger','message'=>'Could not save the item. Check that its slug is unique.'];}}
    $article=array_merge($article?:[],$_POST);
}
$defaultRideReportSlug=$event?slugify(implode('-',array_filter([(string)($event['title']??'ride'),(string)($event['event_date']??''),'event-'.$eventId,'ride-report']))):'';
$article=$article?:['id'=>0,'headline'=>$event?(string)$event['title'].' — Ride Report':'','slug'=>$defaultRideReportSlug,'subheading'=>'','body_html'=>'','results_html'=>'','is_published'=>0,'published_at'=>''];
$dateValue=isset($_POST['publication_date'])?(string)$_POST['publication_date']:(!empty($article['published_at'])?date('Y-m-d',strtotime((string)$article['published_at'])):'');$timeValue=isset($_POST['publication_time'])?(string)$_POST['publication_time']:(!empty($article['published_at'])?date('H:i',strtotime((string)$article['published_at'])):'00:00');$editorTitle=$type==='ride_report'?($id?'Edit Ride Report':'Add Ride Report'):($id?'Edit News':'Add News');admin_layout_start($editorTitle,'news');?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted"><?php echo $type==='ride_report'?'Ride report':'News story'; ?></div><h5 class="mb-0"><?php echo $id?h($article['headline']):h($editorTitle); ?></h5><?php if($event): ?><div class="small text-muted">Linked ride: <?php echo h($event['title']); ?></div><?php endif; ?></div><div><a class="btn btn-outline-secondary" href="<?php echo $type==='ride_report'?'events.php?view=past':'news.php'; ?>">Back</a><?php if($id): ?> <a class="btn btn-outline-primary" href="news_images.php?news_id=<?php echo $id; ?>"><?php echo $type==='ride_report'?'Ride Gallery':'Lead Gallery'; ?></a> <a class="btn btn-success" href="news_sections.php?news_id=<?php echo $id; ?>">Content Sections</a><?php endif; ?></div></div>
<div class="card-soft p-4"><form method="post" class="row g-3"><input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="article_type" value="<?php echo h($type); ?>"><input type="hidden" name="event_id" value="<?php echo $eventId; ?>"><div class="col-md-8"><label class="form-label">Headline / title</label><input required class="form-control" name="headline" value="<?php echo h($article['headline']); ?>"></div><div class="col-md-4"><label class="form-label">Slug</label><input class="form-control" name="slug" value="<?php echo h($article['slug']); ?>"></div><div class="col-12"><label class="form-label">Subheading</label><input class="form-control" name="subheading" value="<?php echo h($article['subheading']??''); ?>"></div><div class="col-12"><label class="form-label"><?php echo $type==='ride_report'?'Ride Report':'Text'; ?></label><textarea class="form-control wysiwyg-field" rows="8" name="body_html"><?php echo h($article['body_html']??''); ?></textarea></div><?php if($type==='ride_report'): ?><div class="col-12"><label class="form-label">Ride Results</label><textarea class="form-control wysiwyg-field" rows="8" name="results_html"><?php echo h($article['results_html']??''); ?></textarea></div><?php endif; ?><div class="col-md-3"><label class="form-label">Publication date</label><input type="date" class="form-control" name="publication_date" value="<?php echo h($dateValue); ?>"></div><div class="col-md-2"><label class="form-label">Publication time</label><select class="form-select" name="publication_time"><?php for($m=0;$m<1440;$m+=15):$option=sprintf('%02d:%02d',intdiv($m,60),$m%60);?><option value="<?php echo $option; ?>" <?php echo $timeValue===$option?'selected':''; ?>><?php echo $option; ?></option><?php endfor; ?></select><div class="form-text">15-minute intervals only.</div></div><div class="col-md-3 form-check mt-5"><input class="form-check-input" type="checkbox" name="is_published" id="pub" <?php echo !empty($article['is_published'])?'checked':''; ?>><label class="form-check-label" for="pub">Published</label></div><div class="col-12"><button class="btn btn-success">Save <?php echo $type==='ride_report'?'Ride Report':'News'; ?></button></div></form></div>
<?php render_tinymce_bootstrap(); ?><script>tinymce.init(window.ildraNewsTinyMceConfig('textarea.wysiwyg-field'));</script><?php admin_layout_end();
