<?php
declare(strict_types=1);require __DIR__.'/_bootstrap.php';
if(!in_array(strtolower((string)($currentUser['role']??'')),['superadmin','admin','organiser'],true)){header('Location:index.php');exit;}
ensureNewsTables($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='delete'){$id=(int)($_POST['id']??0);if($id>0){$pdo->prepare('DELETE FROM news_content_sections WHERE news_id=:id')->execute([':id'=>$id]);$pdo->prepare('DELETE FROM news_articles WHERE id=:id')->execute([':id'=>$id]);}header('Location:news.php');exit;}
$articles=fetchNewsArticles($pdo);admin_layout_start('News','news');?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">News content</div><h5 class="mb-0">News</h5></div><a class="btn btn-success" href="news_edit.php">Add News</a></div>
<div class="card-soft p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Headline</th><th>Type</th><th>Published</th><th>Date</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($articles as $article): ?><tr><td><strong><?php echo h($article['headline']); ?></strong><div class="small text-muted"><?php echo h($article['subheading']??''); ?></div></td><td><?php echo ($article['article_type']??'news')==='ride_report'?'Ride report':'News'; ?></td><td><?php echo $article['is_published']?'Yes':'No'; ?></td><td><?php echo h(format_display_datetime($article['published_at']??null,'—')); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-success" href="news_edit.php?id=<?php echo (int)$article['id']; ?>">Edit</a> <a class="btn btn-sm btn-outline-primary" target="_blank" href="<?php echo h($siteBase); ?>/news/<?php echo (int)$article['id']; ?>-<?php echo h($article['slug']); ?>">View</a> <form method="post" class="d-inline" onsubmit="return confirm('Delete this item?');"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?php echo (int)$article['id']; ?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach; ?><?php if(!$articles): ?><tr><td colspan="5" class="text-muted">No news items yet.</td></tr><?php endif; ?></tbody></table></div></div>
<?php admin_layout_end();
