<?php
declare(strict_types=1);
require __DIR__.'/_bootstrap.php'; require_once __DIR__.'/table_sort.php';
if(!in_array(strtolower((string)($currentUser['role']??'')),['superadmin','admin','manager','organiser'],true)){header('Location:index.php');exit;}
ensureNewsTables($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='delete'){$id=(int)($_POST['id']??0);if($id>0){$pdo->prepare('DELETE FROM news_content_sections WHERE news_id=:id')->execute([':id'=>$id]);$pdo->prepare('DELETE FROM news_articles WHERE id=:id')->execute([':id'=>$id]);}header('Location:news.php');exit;}
$columns=['headline'=>['label'=>'Headline','sortable'=>true,'filter'=>'text','placeholder'=>'Search headline','value'=>static fn(array $r):string=>(string)$r['headline']],'type'=>['label'=>'Type','sortable'=>true,'filter'=>'select','options'=>['news'=>'News','ride_report'=>'Ride report'],'value'=>static fn(array $r):string=>(string)($r['article_type']??'news')],'creator'=>['label'=>'Creator','sortable'=>true,'filter'=>'text','placeholder'=>'Search creator','value'=>static fn(array $r):string=>(string)($r['creator_name']?:($r['creator_email']??''))],'published'=>['label'=>'Published','sortable'=>true,'filter'=>'select','options'=>['1'=>'Yes','0'=>'No'],'value'=>static fn(array $r):string=>!empty($r['is_published'])?'1':'0'],'date'=>['label'=>'Date','sortable'=>true,'filter'=>'date','value'=>static fn(array $r):string=>(string)($r['published_at']??''),'sort_value'=>static fn(array $r):string=>(string)($r['published_at']??$r['created_at']??'')]];
$table=admin_table_prepare(fetchNewsArticles($pdo),$columns,'date','desc');$articles=$table['rows'];$filters=$table['filters'];$sortKey=$table['sort_key'];$sortDir=$table['sort_dir'];
admin_layout_start('News','news'); ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">News content</div><h5 class="mb-0">News</h5></div><a class="btn btn-success" href="news_edit.php">Add News</a></div>
<div class="card-soft p-3"><form method="get" id="news-filter-form" class="text-end mb-2"><button class="btn btn-sm btn-outline-secondary">Filter</button> <a class="btn btn-sm btn-link" href="news.php">Clear</a></form><?php echo admin_table_record_count($table,'article','articles'); ?><div class="table-responsive"><table class="table align-middle"><thead><tr><?php foreach($columns as $key=>$column): ?><th><?php echo admin_table_heading($key,$column,$sortKey,$sortDir); ?></th><?php endforeach; ?><th class="text-end">Actions</th></tr><tr class="admin-table-filter-row"><?php foreach($columns as $key=>$column): ?><th><?php echo admin_table_filter($key,$column,$filters); ?></th><?php endforeach; ?><th></th></tr></thead><tbody><?php foreach($articles as $article): ?><tr><td><strong><?php echo h($article['headline']); ?></strong><div class="small text-muted"><?php echo h($article['subheading']??''); ?></div></td><td><?php echo ($article['article_type']??'news')==='ride_report'?'Ride report':'News'; ?></td><td><?php echo h((string)($article['creator_name']?:($article['creator_email']??'—'))); ?></td><td><?php echo $article['is_published']?'Yes':'No'; ?></td><td><?php echo h(format_display_datetime($article['published_at']??null,'—')); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-success" href="news_edit.php?id=<?php echo (int)$article['id']; ?>">Edit</a> <a class="btn btn-sm btn-outline-primary" target="_blank" href="<?php echo h($siteBase); ?>/news/<?php echo (int)$article['id']; ?>-<?php echo h($article['slug']); ?>">View</a> <form method="post" class="d-inline" onsubmit="return confirm('Delete this item?');"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?php echo (int)$article['id']; ?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach; ?><?php if(!$articles): ?><tr><td colspan="6" class="text-muted">No news items match the current filters.</td></tr><?php endif; ?></tbody></table></div><?php echo admin_table_pagination($table); ?></div>
<?php admin_layout_end();
