<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';

if (!in_array(strtolower((string)($currentUser['role'] ?? '')), ['superadmin','admin'], true)) { header('Location: index.php'); exit; }
$pageId=max(0,(int)($_GET['page_id']??$_POST['page_id']??0));
$page=$pageId?fetchPageById($pdo,$pageId):null;
if(!$page){ $_SESSION['flash_alerts']=[['type'=>'danger','message'=>'Page not found.']]; header('Location: pages.php'); exit; }
$batch=mediaBatchGetOrCreate($pdo,'page_images','page',$pageId,'Images for '.$page['title'],'page-images');

if($_SERVER['REQUEST_METHOD']==='POST'&&$batch){
    $action=(string)($_POST['action']??'upload');
    if($action==='upload'){
        $errors=[];$count=mediaBatchUpload($pdo,$batch,$_FILES['images']??[],['original'=>null,'lg'=>1200,'md'=>600,'sm'=>300,'xs'=>150],$errors);
        foreach($errors as $error)$alerts[]=['type'=>'danger','message'=>$error];
        if($count){$_SESSION['flash_success']=$count.($count===1?' image':' images').' uploaded.';header('Location: page_images.php?page_id='.$pageId);exit;}
    }elseif($action==='save_images'){
        $allowed=array_column(mediaBatchImages($pdo,(int)$batch['id'],true),null,'id');
        foreach((array)($_POST['image']??[])as$id=>$values){$id=(int)$id;if(!isset($allowed[$id]))continue;$stmt=$pdo->prepare('UPDATE media_batch_images SET title=:title,alt_text=:alt,caption=:caption,display_order=:ord,archived=:archived,updated_at=NOW() WHERE id=:id AND batch_id=:batch');$stmt->execute([':title'=>trim((string)($values['title']??''))?:null,':alt'=>trim((string)($values['alt_text']??''))?:null,':caption'=>trim((string)($values['caption']??''))?:null,':ord'=>(int)($values['display_order']??100),':archived'=>!empty($values['archived'])?1:0,':id'=>$id,':batch'=>$batch['id']]);}
        $_SESSION['flash_success']='Page images updated.';header('Location: page_images.php?page_id='.$pageId);exit;
    }
}
$images=mediaBatchImages($pdo,(int)$batch['id'],true);
admin_layout_start('Page Images','pages'); ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Page Images</div><h5 class="mb-0"><?php echo h($page['title']); ?></h5></div><div><a class="btn btn-outline-secondary" href="page_edit.php?id=<?php echo $pageId; ?>">Back to Page</a> <a class="btn btn-outline-primary" target="_blank" href="<?php echo h($siteBase); ?>/pages/<?php echo h($page['slug']); ?>">View Page</a></div></div>
<div class="card-soft p-4 mb-4"><h6>Upload images</h6><form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="upload"><input type="hidden" name="page_id" value="<?php echo $pageId; ?>"><label id="page-drop-zone" class="d-block border border-2 border-secondary-subtle rounded-3 p-4 text-center bg-light" style="cursor:pointer"><input class="visually-hidden" id="page-images" type="file" name="images[]" accept="image/jpeg,image/png,image/gif,image/webp" multiple required><span class="d-block fs-5 fw-semibold">Drop images here</span><span class="d-block text-muted">or click to browse</span><span id="page-file-summary" class="d-block small mt-2 text-success"></span></label><div class="form-text">Creates original, 1200px, 600px, 300px and 150px versions.</div><button class="btn btn-success mt-3">Upload Images</button></form></div>
<div class="card-soft p-3"><form method="post"><input type="hidden" name="action" value="save_images"><input type="hidden" name="page_id" value="<?php echo $pageId; ?>"><div class="small text-muted mb-3">The first active image is the main image. Remaining images appear as thumbnails in order.</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Preview</th><th style="width:90px">Order</th><th>Title / alt text / caption</th><th>State</th></tr></thead><tbody><?php foreach($images as $index=>$image): ?><tr><td style="width:220px"><img src="<?php echo h(mediaBatchImageUrl($batch,$image,'sm')); ?>" alt="" style="width:200px;max-height:100px;object-fit:cover" class="rounded border"><?php if($index===0&&!$image['archived']): ?><div><span class="badge bg-success mt-1">Main image</span></div><?php endif; ?></td><td><input class="form-control" type="number" name="image[<?php echo (int)$image['id']; ?>][display_order]" value="<?php echo (int)$image['display_order']; ?>"></td><td><input class="form-control form-control-sm mb-1" name="image[<?php echo (int)$image['id']; ?>][title]" value="<?php echo h($image['title']??''); ?>" placeholder="Title"><input class="form-control form-control-sm mb-1" name="image[<?php echo (int)$image['id']; ?>][alt_text]" value="<?php echo h($image['alt_text']??''); ?>" placeholder="Alternative text"><textarea class="form-control form-control-sm" name="image[<?php echo (int)$image['id']; ?>][caption]" rows="2" placeholder="Caption"><?php echo h($image['caption']??''); ?></textarea></td><td><div class="form-check"><input class="form-check-input" type="checkbox" name="image[<?php echo (int)$image['id']; ?>][archived]" value="1" id="arch-<?php echo (int)$image['id']; ?>" <?php echo !empty($image['archived'])?'checked':''; ?>><label class="form-check-label" for="arch-<?php echo (int)$image['id']; ?>">Archived</label></div></td></tr><?php endforeach; ?><?php if(!$images): ?><tr><td colspan="4" class="text-muted">No page images yet.</td></tr><?php endif; ?></tbody></table></div><?php if($images): ?><button class="btn btn-success">Save Images</button><?php endif; ?></form></div>
<script>(function(){const z=document.getElementById('page-drop-zone'),i=document.getElementById('page-images'),s=document.getElementById('page-file-summary');function show(){const f=Array.from(i.files||[]);s.textContent=f.length?f.length+(f.length===1?' image selected: ':' images selected: ')+f.map(x=>x.name).join(', '):'';}['dragenter','dragover'].forEach(t=>z.addEventListener(t,e=>{e.preventDefault();z.classList.add('border-success','bg-success-subtle');}));['dragleave','drop'].forEach(t=>z.addEventListener(t,e=>{e.preventDefault();z.classList.remove('border-success','bg-success-subtle');}));z.addEventListener('drop',e=>{if(e.dataTransfer&&e.dataTransfer.files.length){i.files=e.dataTransfer.files;show();}});i.addEventListener('change',show);})();</script>
<?php admin_layout_end();
