<?php
declare(strict_types=1);
require __DIR__.'/_bootstrap.php';
if(!in_array(strtolower((string)($currentUser['role']??'')),['superadmin','admin'],true)){header('Location:index.php');exit;}
$pageId=max(0,(int)($_GET['page_id']??$_POST['page_id']??0));$page=$pageId?fetchPageById($pdo,$pageId):null;
if(!$page){$_SESSION['flash_alerts']=[['type'=>'danger','message'=>'Page not found.']];header('Location:pages.php');exit;}
function page_element_anchor(string $value): string{return image_upload_slug($value);}
ensurePageContentElementsTable($pdo);$edit=(string)($_GET['edit']??'');$editId=ctype_digit($edit)?(int)$edit:0;$record=$editId?fetchPageContentElement($pdo,$editId):($edit==='new'?['id'=>0,'name'=>'','heading'=>'','anchor_slug'=>'','body_html'=>'','layout'=>'auto','display_order'=>100,'show_on_web'=>1,'archived'=>0]:null);
if($record&&(int)($record['page_id']??$pageId)!==$pageId)$record=null;
if($_SERVER['REQUEST_METHOD']==='POST'){$action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);
if($action==='delete'){$pdo->prepare('DELETE FROM page_content_elements WHERE id=:id AND page_id=:page')->execute([':id'=>$id,':page'=>$pageId]);$_SESSION['flash_success']='Content section deleted.';header('Location:page_elements.php?page_id='.$pageId);exit;}
$name=trim((string)($_POST['name']??''));$heading=trim((string)($_POST['heading']??''));$anchor=page_element_anchor(trim((string)($_POST['anchor_slug']??''))?:($heading?:$name));$body=trim((string)($_POST['body_html']??''));$layout=in_array($_POST['layout']??'auto',['auto','image_left','image_right','text_only'],true)?$_POST['layout']:'auto';if($name==='')$alerts[]=['type'=>'danger','message'=>'Section name is required.'];$check=$pdo->prepare('SELECT id FROM page_content_elements WHERE page_id=:page AND anchor_slug=:anchor AND id<>:id LIMIT 1');$check->execute([':page'=>$pageId,':anchor'=>$anchor,':id'=>$id]);if($check->fetchColumn())$alerts[]=['type'=>'danger','message'=>'That anchor is already used on this page.'];
if(!$alerts){$data=[':page'=>$pageId,':name'=>$name,':heading'=>$heading?:null,':anchor'=>$anchor,':body'=>$body?:null,':layout'=>$layout,':ord'=>(int)($_POST['display_order']??100),':show'=>!empty($_POST['show_on_web'])?1:0,':archived'=>!empty($_POST['archived'])?1:0];if($id){$data[':id']=$id;$sql='UPDATE page_content_elements SET name=:name,heading=:heading,anchor_slug=:anchor,body_html=:body,layout=:layout,display_order=:ord,show_on_web=:show,archived=:archived,updated_at=NOW() WHERE id=:id AND page_id=:page';}else{$sql='INSERT INTO page_content_elements(page_id,name,heading,anchor_slug,body_html,layout,display_order,show_on_web,archived) VALUES(:page,:name,:heading,:anchor,:body,:layout,:ord,:show,:archived)';}$pdo->prepare($sql)->execute($data);$_SESSION['flash_success']='Content section saved.';header('Location:page_elements.php?page_id='.$pageId);exit;}$record=array_merge($record?:[],$_POST,['id'=>$id]);}
$isEditor=(bool)$record;$elements=fetchPageContentElements($pdo,$pageId);admin_layout_start('Page Content Sections','pages');?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><div class="small text-muted">Content Sections</div><h5 class="mb-0"><?php echo h($page['title']); ?></h5></div><div><a class="btn btn-outline-secondary" href="page_edit.php?id=<?php echo $pageId; ?>">Back to Page</a><?php if(!$isEditor): ?> <a class="btn btn-success" href="page_elements.php?page_id=<?php echo $pageId; ?>&edit=new">Add New</a><?php endif; ?></div></div>
<?php if($isEditor && !empty($record['anchor_slug'])): $anchorUrl=($siteBase?:'').'/pages/'.$page['slug'].'#'.$record['anchor_slug']; ?>
<div class="small mb-3"><span aria-hidden="true">&#128279;</span> <button type="button" class="btn btn-link btn-sm p-0 text-decoration-none" title="Copy anchor link" onclick="navigator.clipboard.writeText(document.getElementById('element-anchor-url').value)">#<?php echo h($record['anchor_slug']); ?></button><input id="element-anchor-url" type="hidden" value="<?php echo h($anchorUrl); ?>"><span class="text-muted ms-1">Click to copy</span></div>
<?php endif; ?>
<?php if($isEditor): ?><div class="card-soft p-4"><form method="post" class="row g-3"><input type="hidden" name="page_id" value="<?php echo $pageId; ?>"><input type="hidden" name="id" value="<?php echo (int)($record['id']??0); ?>"><div class="col-md-6"><label class="form-label">Internal name</label><input class="form-control" required name="name" value="<?php echo h($record['name']??''); ?>"></div><div class="col-md-6"><label class="form-label">Heading</label><input class="form-control" name="heading" value="<?php echo h($record['heading']??''); ?>"></div><div class="col-12"><label class="form-label">Content</label><textarea id="elementBody" class="form-control wysiwyg-field" rows="10" name="body_html"><?php echo h($record['body_html']??''); ?></textarea></div><div class="col-md-4"><label class="form-label">Layout</label><select class="form-select" name="layout"><?php foreach(['auto'=>'Automatic','image_left'=>'Image left','image_right'=>'Image right','text_only'=>'Text only'] as$v=>$l): ?><option value="<?php echo $v; ?>" <?php echo ($record['layout']??'auto')===$v?'selected':''; ?>><?php echo $l; ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Order</label><input class="form-control" type="number" name="display_order" value="<?php echo (int)($record['display_order']??100); ?>"></div><div class="col-md-2 form-check mt-5"><input class="form-check-input" type="checkbox" name="show_on_web" id="show" <?php echo !empty($record['show_on_web'])?'checked':''; ?>><label for="show">Show on web</label></div><div class="col-md-2 form-check mt-5"><input class="form-check-input" type="checkbox" name="archived" id="archive" <?php echo !empty($record['archived'])?'checked':''; ?>><label for="archive">Archived</label></div><div class="col-12"><button class="btn btn-success">Save Section</button> <a class="btn btn-outline-secondary" href="page_elements.php?page_id=<?php echo $pageId; ?>">Cancel</a></div></form></div><?php render_tinymce_bootstrap(); ?><script>tinymce.init(window.ildraTinyMceConfig({selector:'textarea.wysiwyg-field'}));</script>
<?php else: ?><div class="card-soft p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Order</th><th>Name / heading</th><th>Layout</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($elements as$element): ?><tr><td><?php echo (int)$element['display_order']; ?></td><td><strong><?php echo h($element['name']); ?></strong><div class="small text-muted"><?php echo h($element['heading']?:''); ?></div></td><td><?php echo h(ucwords(str_replace('_',' ',$element['layout']))); ?></td><td><?php echo !empty($element['archived'])?'Archived':(!empty($element['show_on_web'])?'Visible':'Hidden'); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="page_elements.php?page_id=<?php echo $pageId; ?>&edit=<?php echo (int)$element['id']; ?>">Edit</a> <a class="btn btn-sm btn-outline-primary" href="element_images.php?element_id=<?php echo (int)$element['id']; ?>">Images</a> <form class="d-inline" method="post" onsubmit="return confirm('Delete this section?');"><input type="hidden" name="page_id" value="<?php echo $pageId; ?>"><input type="hidden" name="id" value="<?php echo (int)$element['id']; ?>"><input type="hidden" name="action" value="delete"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach; ?><?php if(!$elements): ?><tr><td colspan="5" class="text-muted">No additional content sections yet.</td></tr><?php endif; ?></tbody></table></div></div><?php endif;admin_layout_end();
