<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';

$eventId=max(0,(int)($_GET['event_id']??$_POST['event_id']??0)); $event=fetchEventById($pdo,$eventId);
if(!$event){http_response_code(404);$alerts[]=['type'=>'danger','message'=>'Event not found.'];admin_layout_start('Ride Notes','events');admin_layout_end();exit;}
ensureRideNotesTables($pdo); if(empty($_SESSION['ride_notes_csrf']))$_SESSION['ride_notes_csrf']=bin2hex(random_bytes(24)); $csrf=(string)$_SESSION['ride_notes_csrf']; $siteSettings=getSiteSettings($pdo); $notes=fetchRideNotes($pdo,$eventId)?:['status'=>'draft','intro_html'=>'','ride_notes_html'=>'','ctr_notes_html'=>'']; $batch=mediaBatchGetOrCreate($pdo,'ride_notes_images','event',$eventId,'Ride Notes images: '.(string)$event['title'],'ride-notes');
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??''))) $alerts[]=['type'=>'danger','message'=>'Your session token expired. Please try again.'];
    else { $action=(string)($_POST['action']??'');
        if($action==='save'){if(saveRideNotes($pdo,$eventId,$_POST,(int)$currentUser['id'])){$_SESSION['flash_success']='Ride Notes saved.';header('Location: ride_notes.php?event_id='.$eventId);exit;}$alerts[]=['type'=>'danger','message'=>'Ride Notes could not be saved.'];}
        elseif($action==='upload_images'){$errors=[];$count=mediaBatchUpload($pdo,$batch,$_FILES['images']??[],['original'=>null,'lg'=>1400,'md'=>800,'sm'=>400,'xs'=>180],$errors);foreach($errors as $error)$alerts[]=['type'=>'danger','message'=>$error];if($count){$_SESSION['flash_success']=$count.($count===1?' image uploaded.':' images uploaded.');header('Location: ride_notes.php?event_id='.$eventId);exit;}}
        elseif($action==='upload_pdf'){$error=null;$stored=rideNotesStorePdf($_FILES['ride_notes_pdf']??[],$event,$error);if(!$stored)$alerts[]=['type'=>'danger','message'=>$error?:'Unable to upload the Ride Notes PDF.'];elseif(saveRideNotesPdf($pdo,$eventId,$stored)){$_SESSION['flash_success']='Ride Notes PDF uploaded.';header('Location: ride_notes.php?event_id='.$eventId);exit;}else $alerts[]=['type'=>'danger','message'=>'The PDF was uploaded but could not be recorded.'];}
        elseif($action==='send_test'){$recipients=parseEmailList((string)($_POST['test_recipients']??''));if(($notes['status']??'draft')!=='published')$alerts[]=['type'=>'warning','message'=>'Publish the Ride Notes before sending a full email test. Use Preview while they are still a draft.'];elseif(!$recipients)$alerts[]=['type'=>'danger','message'=>'Enter one or more valid test email addresses.'];else{$settings=getEmailSettings($pdo);$payload=rideNotesEmailPayload($event,$notes,$siteSettings,$settings,$siteBase);$attachment=rideNotesPdfAttachment($notes);$sent=0;foreach($recipients as $recipient)if(send_logged_email($pdo,$recipient,$payload['subject'],$payload['html'],$payload['text'],['kind'=>'ride_notes_test','event_id'=>$eventId,'admin_user_id'=>(int)$currentUser['id']],$attachment?[$attachment]:[]))$sent++;$alerts[]=['type'=>$sent===count($recipients)?'success':'warning','message'=>$sent.' of '.count($recipients).' test email'.(count($recipients)===1?' was':'s were').' sent. Check Email logs for details.'];}}
        elseif($action==='create_campaign'){
            if(($notes['status']??'draft')!=='published')$alerts[]=['type'=>'warning','message'=>'Publish the Ride Notes before creating its campaign.'];
            else{
                ensureEmailCampaignTables($pdo);$templateStmt=$pdo->prepare("SELECT * FROM email_campaign_templates WHERE template_key='ride_notes' LIMIT 1");$templateStmt->execute();$campaignTemplate=$templateStmt->fetch()?:[];
                $campaignSubject=(string)($campaignTemplate['subject_template']??'Ride Notes: {{event_title}}');
                $campaignHtml=(string)($campaignTemplate['html_template']??'<h2>Ride Notes</h2><p>Hello {{first_name}},</p><p>Important information for <strong>{{event_title}}</strong> on {{event_date}} is now available.</p><p><a href="{{ride_notes_url}}">View Ride Notes</a></p>');
                $campaignText=(string)($campaignTemplate['text_template']??"Ride Notes\n\nHello {{first_name}},\n\nImportant information for {{event_title}} on {{event_date}} is now available.\n\n{{ride_notes_url}}");
                $existing=$pdo->prepare("SELECT id FROM email_campaigns WHERE campaign_type='ride_notes' AND event_id=:event AND status NOT IN ('cancelled','sent') ORDER BY id DESC LIMIT 1");$existing->execute([':event'=>$eventId]);$campaignId=(int)($existing->fetchColumn()?:0);
                if(!$campaignId){$stmt=$pdo->prepare("INSERT INTO email_campaigns (name,campaign_type,category,template_id,audience_preset,event_id,membership_year,address_strategy,subject_template,html_template,text_template,batch_size,created_by_user_id) VALUES (:name,'ride_notes','operational',:template,'event_entrants',:event,:year,'person_first',:subject,:html,:text,:batch,:user)");$stmt->execute([':name'=>'Ride Notes - '.(string)$event['title'],':template'=>(int)($campaignTemplate['id']??0)?:null,':event'=>$eventId,':year'=>(int)date('Y'),':subject'=>$campaignSubject,':html'=>$campaignHtml,':text'=>$campaignText,':batch'=>max(1,(int)($siteSettings['campaign_default_batch_size']??25)),':user'=>(int)$currentUser['id']]);$campaignId=(int)$pdo->lastInsertId();}
                header('Location: campaigns.php?view=edit&id='.$campaignId);exit;
            }
        }
    } $notes=array_merge($notes,$_POST);
}
$images=$batch?mediaBatchImages($pdo,(int)$batch['id']):[];$defaultIntro=rideNotesDefaultSettings($siteSettings)['intro_html'];admin_layout_start('Ride Notes','events');
?>
<style>
    .card-soft form .col-md-3:has(select[name="status"]) { display:grid; grid-template-columns:minmax(150px, 220px) minmax(0, 1fr); column-gap:1rem; align-items:center; width:100%; }
    .card-soft form .col-md-3:has(select[name="status"]) > label { grid-column:1 / -1; }
    .card-soft form .col-md-3:has(select[name="status"]) > select { grid-column:1; grid-row:2; }
    .card-soft form .col-md-3:has(select[name="status"]) > .form-text { grid-column:2; grid-row:2; margin-top:0; }
    @media (max-width:575.98px) { .card-soft form .col-md-3:has(select[name="status"]) { display:block; } .card-soft form .col-md-3:has(select[name="status"]) > .form-text { margin-top:.25rem; } }
</style>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><div class="small text-muted"><?php echo h(format_display_date($event['event_date']??null,'')); ?></div><h5 class="mb-0">Ride Notes — <?php echo h($event['title']); ?></h5></div><div class="d-flex flex-wrap align-items-center gap-2"><a class="btn btn-outline-primary" target="_blank" rel="noopener" href="../ride_notes.php?event_id=<?php echo $eventId; ?>&amp;preview=1">Preview</a><form method="post" class="m-0"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="create_campaign"><input type="hidden" name="event_id" value="<?php echo $eventId; ?>"><button class="btn btn-success" <?php echo ($notes['status']??'draft')!=='published'?'disabled':''; ?>>Create email campaign</button></form><a class="btn btn-outline-secondary" href="events.php?view=future">Back to events</a></div></div>
<div class="card-soft p-4 mb-4"><form method="post"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="event_id" value="<?php echo $eventId; ?>"><div class="row g-3"><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="draft" <?php echo $notes['status']==='draft'?'selected':''; ?>>Draft</option><option value="published" <?php echo $notes['status']==='published'?'selected':''; ?>>Published</option><option value="hidden" <?php echo $notes['status']==='hidden'?'selected':''; ?>>Hidden</option></select><div class="form-text">Published notes are shown to signed-in users. Hidden notes are retained but unavailable to riders.</div></div><div class="col-12"><label class="form-label">Email intro text</label><textarea class="form-control wysiwyg-field" rows="5" name="intro_html"><?php echo h($notes['intro_html']?:$defaultIntro); ?></textarea><div class="form-text">Overrides the default Ride Notes email intro in Settings.</div></div><div class="col-12"><label class="form-label">Ride Notes</label><textarea class="form-control wysiwyg-field" rows="10" name="ride_notes_html"><?php echo h($notes['ride_notes_html']); ?></textarea></div><div class="col-12"><label class="form-label">CTR Notes</label><textarea class="form-control wysiwyg-field" rows="8" name="ctr_notes_html"><?php echo h($notes['ctr_notes_html']); ?></textarea></div><div class="col-12"><button class="btn btn-success">Save Ride Notes</button></div></div></form></div>
<div class="row g-4"><div class="col-lg-6"><div class="card-soft p-4 h-100"><h6>Images</h6><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="upload_images"><input type="hidden" name="event_id" value="<?php echo $eventId; ?>"><input class="form-control" type="file" name="images[]" accept="image/jpeg,image/png,image/gif,image/webp" multiple required><div class="form-text">Bulk upload JPG, PNG, GIF or WebP images.</div><button class="btn btn-outline-success mt-3">Upload images</button></form><?php if($images): ?><div class="d-flex flex-wrap gap-2 mt-3"><?php foreach($images as $image): ?><img class="rounded border" style="width:120px;height:90px;object-fit:cover" src="<?php echo h(mediaBatchImageUrl($batch,$image,'sm')); ?>" alt="<?php echo h($image['alt_text']??''); ?>"><?php endforeach; ?></div><?php endif; ?></div></div><div class="col-lg-3"><div class="card-soft p-4 h-100"><h6>Ride Notes PDF</h6><p class="small text-muted">Optional document; shown to riders and attached to Ride Notes emails.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="upload_pdf"><input type="hidden" name="event_id" value="<?php echo $eventId; ?>"><input class="form-control" type="file" name="ride_notes_pdf" accept="application/pdf,.pdf" required><div class="form-text">PDF only; up to 10 MB.</div><button class="btn btn-outline-success mt-3">Upload PDF</button></form><?php if(!empty($notes['pdf_filename'])): ?><div class="mt-3 small"><a target="_blank" rel="noopener" href="<?php echo h(rideNotesPdfUrl((string)$notes['pdf_filename'])); ?>"><i class="fa-solid fa-file-pdf text-danger"></i> <?php echo h((string)($notes['pdf_original_filename']?:$notes['pdf_filename'])); ?></a></div><?php endif; ?></div></div><div class="col-lg-3"><div class="card-soft p-4 h-100"><h6>Test send</h6><p class="small text-muted">Sends only to these addresses. Live entry-recipient sending is not enabled yet.</p><form method="post"><input type="hidden" name="csrf" value="<?php echo h($csrf); ?>"><input type="hidden" name="action" value="send_test"><input type="hidden" name="event_id" value="<?php echo $eventId; ?>"><label class="form-label" for="test-recipients">Test recipients</label><input class="form-control" id="test-recipients" name="test_recipients" value="<?php echo h((string)($_POST['test_recipients']??$currentUser['email']??'')); ?>" placeholder="name@example.com, second@example.com"><div class="form-text">Separate addresses with commas.</div><button class="btn btn-outline-primary mt-3">Send test email</button></form></div></div></div>
<?php render_tinymce_bootstrap(); ?><script>if(window.tinymce)tinymce.init(window.ildraTinyMceConfig({selector:'textarea.wysiwyg-field'}));</script><?php admin_layout_end();
